# SPDX-License-Identifier: Apache-2.0
"""Build ``catalog/<family>/<PRIM>.yaml`` from UNISIM model headers and UG953 text.

UNISIM is authoritative for port/parameter names, directions, widths and
defaults. UG953 supplies group/subgroup, a short description, allowed values,
the documented attribute type, design-entry support and the page number. Every
name found in only one of the two sources is reported, never dropped.
"""

from pathlib import Path

import yaml

from xut.catalog.model import CatalogEntry, validate
from xut.catalog.portclass import default_class
from xut.catalog.ug953 import DocSection, split_sections
from xut.catalog.unisim import find_model, parse_module
from xut.docs_fetch import UG953

FAMILY = "7series"
HEADER = (
    "# SPDX-License-Identifier: Apache-2.0\n"
    "# GENERATED by xut catalog build — edit {name}.overrides.yaml instead\n"
)


def _entry(name: str, sec: DocSection | None, model, library: str) -> CatalogEntry:
    doc_ports = sec.ports if sec else {}
    doc_attrs = sec.attributes if sec else {}
    ports: list[dict] = []
    attrs: list[dict] = []
    if model is not None:
        for p in model.ports:
            ports.append(
                {
                    "name": p.name,
                    "direction": p.direction,
                    "width": p.width,
                    "cls": default_class(name, p.name, p.direction),
                    "doc_function": doc_ports.get(p.name, {}).get("function", ""),
                }
            )
        for a in model.params:
            d = doc_attrs.get(a.name, {})
            attrs.append(
                {
                    "name": a.name,
                    "kind": a.kind,
                    "width": a.width,
                    "default": a.default,
                    "allowed": list(d.get("allowed", [])),
                    "doc_type": d.get("type"),
                }
            )
    else:
        for pname, d in doc_ports.items():
            ports.append(
                {
                    "name": pname,
                    "direction": d["direction"],
                    "width": d["width"],
                    "cls": default_class(name, pname, d["direction"]),
                    "doc_function": d["function"],
                }
            )
        for aname, d in doc_attrs.items():
            attrs.append(
                {
                    "name": aname,
                    "kind": None,
                    "width": None,
                    "default": d["default"] or None,
                    "allowed": list(d["allowed"]),
                    "doc_type": d["type"],
                }
            )
    return CatalogEntry(
        name=name,
        family=FAMILY,
        group=sec.group if sec else "",
        subgroup=sec.subgroup if sec else "",
        description=sec.description if sec else "",
        doc={
            "guide": UG953.name.upper(),
            "edition": UG953.edition,
            "page": sec.page if sec else None,
        },
        model={"library": library, "file": model.source.name if model is not None else None},
        ports=ports,
        attributes=attrs,
        design_entry=dict(sec.design_entry) if sec else {},
        claims=[],
        status_undocumented=sec is None,
    )


def _compare(name: str, sec: DocSection, model) -> list[str]:
    out: list[str] = []
    hdl_ports = {p.name: p for p in model.ports}
    hdl_params = {p.name for p in model.params}
    if not sec.ports:
        out.append(f"{name}: no Port Descriptions table in UG953 (ports from unisim only)")
    else:
        for p in model.ports:
            if p.name not in sec.ports:
                out.append(f"{name}: port {p.name} only in unisim")
        for p, d in sec.ports.items():
            if p not in hdl_ports:
                out.append(f"{name}: port {p} only in ug953")
            else:
                h = hdl_ports[p]
                if h.direction != d["direction"]:
                    out.append(
                        f"{name}: port {p} direction unisim={h.direction} ug953={d['direction']}"
                    )
                if h.width != d["width"]:
                    out.append(f"{name}: port {p} width unisim={h.width} ug953={d['width']}")
    if not sec.attributes:
        if hdl_params:
            out.append(
                f"{name}: no Available Attributes table in UG953 "
                f"({len(hdl_params)} unisim parameter(s): {', '.join(sorted(hdl_params))})"
            )
    else:
        for a in model.params:
            if a.name not in sec.attributes:
                out.append(f"{name}: attribute {a.name} only in unisim")
        for a in sec.attributes:
            if a not in hdl_params:
                out.append(f"{name}: attribute {a} only in ug953")
    return out


def _dump(entry: CatalogEntry) -> str:
    body = yaml.safe_dump(
        entry.to_dict(), sort_keys=False, allow_unicode=True, width=100, default_flow_style=False
    )
    return HEADER.format(name=entry.name) + body


def build_all(text_path: Path, names: list[str], out_dir: Path, search: list[Path]) -> list[str]:
    """Write ``<out_dir>/<PRIM>.yaml`` for every name; return the report lines."""
    out_dir = Path(out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    sections = split_sections(Path(text_path).read_text(), names)
    report: list[str] = []
    for name in names:
        sec = sections.get(name)
        found = find_model(name, search)
        model = None
        library = "none"
        if found is not None:
            path, library = found
            model = parse_module(path, name)
        if sec is None:
            report.append(f"{name}: no Primitive section in UG953")
        if model is None:
            report.append(f"{name}: no model found in {', '.join(s.name for s in search)}")
        if sec is not None and model is not None:
            report.extend(_compare(name, sec, model))
        entry = _entry(name, sec, model, library)
        validate(entry.to_dict())
        (out_dir / f"{name}.yaml").write_text(_dump(entry))
    return report
