# SPDX-License-Identifier: Apache-2.0
"""Build ``catalog/<family>/<PRIM>.yaml`` from UNISIM model headers and UG953 text.

UNISIM is authoritative for port/parameter names, directions, widths and
defaults. UG953 supplies group/subgroup, a short description, allowed values,
the documented attribute type, design-entry support and the page number. Every
name found in only one of the two sources is reported, never dropped.
"""

import re
from pathlib import Path

import yaml

from xut.catalog.model import CatalogEntry, is_enumerated, validate
from xut.catalog.portclass import class_note, default_class
from xut.catalog.ug953 import DocSection, split_sections
from xut.catalog.unisim import find_model, parse_module
from xut.docs_fetch import UG953

HEADER = (
    "# SPDX-License-Identifier: Apache-2.0\n"
    "# GENERATED by xut catalog build — edit {name}.overrides.yaml instead\n"
)


def _unquote(v: str) -> str:
    """``"SYNC"`` -> ``SYNC``, matching how UNISIM string defaults are stored."""
    return v[1:-1] if len(v) >= 2 and v[0] == v[-1] == '"' and '"' not in v[1:-1] else v


def _looks_malformed(kind: str, v: str) -> bool:
    if kind == "STRING":
        # a quoted literal, or a phrase such as "String representing file name"
        return not (re.fullmatch(r'"[^"]*"', v) or re.fullmatch(r"[A-Za-z][a-z ]+", v))
    if kind == "BOOLEAN":
        return v.strip('"') not in ("TRUE", "FALSE")
    return '"' in v


_ENUM_TYPES = ("STRING", "BOOLEAN", "DECIMAL")


def value_issues(name: str, sec: DocSection, model=None) -> list[str]:
    """Report lines for UG953 attribute cells the parser could not read cleanly, or that
    disagree with the model: malformed or missing allowed values, duplicates within the
    list, or the UNISIM default missing from an enumerated list."""
    defaults = {p.name: p.default for p in model.params} if model is not None else {}
    out = []
    for attr, d in sec.attributes.items():
        allowed = d["allowed"]
        bad = [v for v in allowed if _looks_malformed(d["type"], v)]
        plain = [_unquote(v) for v in allowed]
        dups = sorted({v for v in plain if plain.count(v) > 1})
        problems = []
        if not allowed:
            problems.append("no allowed values found")
        if bad:
            problems.append(f"unparsed {bad}")
        if dups:
            problems.append(f"duplicate {dups}")
        if (
            attr in defaults
            and d["type"] in _ENUM_TYPES
            and is_enumerated(allowed)
            and str(defaults[attr]) not in plain
        ):
            problems.append(f"unisim default {defaults[attr]!s} not in {plain}")
        if problems:
            out.append(f"{name}: attribute {attr} UG953 values need review ({'; '.join(problems)})")
    return out


def _entry(name: str, sec: DocSection | None, model, library: str, family: str) -> CatalogEntry:
    doc_ports = sec.ports if sec else {}
    doc_attrs = sec.attributes if sec else {}
    ports: list[dict] = []
    attrs: list[dict] = []
    if model is not None:
        for p in model.ports:
            ports.append(
                {
                    "name": p.name,
                    "direction": p.direction,
                    "width": p.width,
                    "cls": default_class(name, p.name, p.direction),
                    "doc_function": doc_ports.get(p.name, {}).get("function", ""),
                }
            )
        for a in model.params:
            d = doc_attrs.get(a.name, {})
            attrs.append(
                {
                    "name": a.name,
                    "kind": a.kind,
                    "width": a.width,
                    "default": a.default,
                    "allowed": [_unquote(v) for v in d.get("allowed", [])],
                    "doc_type": d.get("type"),
                }
            )
    else:
        for pname, d in doc_ports.items():
            ports.append(
                {
                    "name": pname,
                    "direction": d["direction"],
                    "width": d["width"],
                    "cls": default_class(name, pname, d["direction"]),
                    "doc_function": d["function"],
                }
            )
        for aname, d in doc_attrs.items():
            attrs.append(
                {
                    "name": aname,
                    "kind": None,
                    "width": None,
                    "default": _unquote(d["default"]) or None,
                    "allowed": [_unquote(v) for v in d["allowed"]],
                    "doc_type": d["type"],
                }
            )
    return CatalogEntry(
        name=name,
        family=family,
        group=sec.group if sec else "",
        subgroup=sec.subgroup if sec else "",
        description=sec.description if sec else "",
        doc={
            "guide": UG953.name.upper(),
            "edition": UG953.edition,
            "page": sec.page if sec else None,
        },
        model={"library": library, "file": model.source.name if model is not None else None},
        ports=ports,
        attributes=attrs,
        design_entry=dict(sec.design_entry) if sec else {},
        claims=[],
        status_undocumented=sec is None,
    )


def _compare(name: str, sec: DocSection, model) -> list[str]:
    out: list[str] = []
    hdl_ports = {p.name: p for p in model.ports}
    hdl_params = {p.name for p in model.params}
    if not sec.ports:
        out.append(f"{name}: no Port Descriptions table in UG953 (ports from unisim only)")
    else:
        for p in model.ports:
            if p.name not in sec.ports:
                out.append(f"{name}: port {p.name} only in unisim")
        for p, d in sec.ports.items():
            if p not in hdl_ports:
                out.append(f"{name}: port {p} only in ug953")
            else:
                h = hdl_ports[p]
                if h.direction != d["direction"]:
                    out.append(
                        f"{name}: port {p} direction unisim={h.direction} ug953={d['direction']}"
                    )
                if h.width != d["width"]:
                    out.append(f"{name}: port {p} width unisim={h.width} ug953={d['width']}")
    if not sec.attributes:
        if hdl_params:
            out.append(
                f"{name}: no Available Attributes table in UG953 "
                f"({len(hdl_params)} unisim parameter(s): {', '.join(sorted(hdl_params))})"
            )
    else:
        for a in model.params:
            if a.name not in sec.attributes:
                out.append(f"{name}: attribute {a.name} only in unisim")
        for a in sec.attributes:
            if a not in hdl_params:
                out.append(f"{name}: attribute {a} only in ug953")
    return out


def _dump(entry: CatalogEntry) -> str:
    body = yaml.safe_dump(
        entry.to_dict(), sort_keys=False, allow_unicode=True, width=100, default_flow_style=False
    )
    return HEADER.format(name=entry.name) + body


def build_all(
    text_path: Path, names: list[str], out_dir: Path, search: list[Path], *, family: str
) -> list[str]:
    """Write ``<out_dir>/<PRIM>.yaml`` for every name, tagged with `family` (from
    ``xut.workunits.load_family``); return the report lines."""
    out_dir = Path(out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    sections = split_sections(Path(text_path).read_text(), names)
    report: list[str] = []
    for name in names:
        sec = sections.get(name)
        found = find_model(name, search)
        model = None
        library = "none"
        if found is not None:
            path, library = found
            model = parse_module(path, name)
        if sec is None:
            report.append(f"{name}: no Primitive section in UG953")
        if model is None:
            report.append(f"{name}: no model found in {', '.join(s.name for s in search)}")
        if sec is not None and model is not None:
            report.extend(_compare(name, sec, model))
        if sec is not None:
            report.extend(value_issues(name, sec, model))
            for item in sec.review:
                kind, what, cell = item.split()
                report.append(f"{name}: {kind} {what} UG953 {cell} needs review")
        for p in model.ports if model is not None else []:
            note = class_note(name, p.name)
            if note:
                report.append(f"{name}: port {p.name} {note}")
        entry = _entry(name, sec, model, library, family)
        validate(entry.to_dict())
        (out_dir / f"{name}.yaml").write_text(_dump(entry))
    return report


_CATEGORIES = (
    ("Names only in one source", lambda x: " only in " in x),
    ("Width or direction mismatches", lambda x: " width unisim=" in x or " direction unisim=" in x),
    ("Tables absent from UG953", lambda x: ": no Port Descriptions" in x or ": no Available" in x),
    ("UG953 cells needing review", lambda x: " need review " in x or " needs review" in x),
    ("Port class notes", lambda x: " class depends on " in x),
    ("Missing UG953 section or model", lambda x: True),
)


def render_report(report: list[str], names: list[str], sources: str) -> str:
    """Markdown for catalog/EXTRACTION_REPORT.md, grouped by category."""
    groups: dict[str, list[str]] = {title: [] for title, _ in _CATEGORIES}
    for line in report:
        title = next(t for t, match in _CATEGORIES if match(line))
        groups[title].append(line)
    out = [
        "# Catalog extraction report",
        "",
        f"Generated by `xut catalog build` from {UG953.name.upper()} {UG953.edition}",
        f"and {sources}.",
        "Resolve each item with a `<PRIM>.overrides.yaml`, or accept it as a real",
        "difference between the documentation and the model.",
        "",
        f"- primitives: {len(names)}",
        *(f"- {title}: {len(lines)}" for title, lines in groups.items()),
    ]
    for title, lines in groups.items():
        out += ["", f"## {title} ({len(lines)})", ""]
        out += [f"- {line}" for line in lines] or ["None."]
    return "\n".join(out) + "\n"
