// SPDX-License-Identifier: Apache-2.0
// GENERATED by xut wrap: prim=FDRE cfg=init1. Do not edit.
`timescale 1ps / 1ps
module xut_dut (
  input  wire [0:0] clk,
  input  wire [2:0] in_vec,
  output wire [0:0] out_vec
);
  (* DONT_TOUCH = "TRUE", KEEP_HIERARCHY = "TRUE", keep *)
  FDRE #(
    .INIT(1'b1)
  ) dut (
    .Q(out_vec[0]),
    .C(clk[0]),
    .CE(in_vec[0]),
    .D(in_vec[1]),
    .R(in_vec[2])
  );
endmodule
