# SPDX-License-Identifier: Apache-2.0
import re
import shutil
from pathlib import Path

import pyslang
import pytest

from xut.container import SIM_IMAGE, DockerExecutor, image_digest
from xut.paths import repo_root
from xut.verilatorize.analyze import TransformError, analyze, generate_configs
from xut.verilatorize.rewrite import check_clean, rewrite, write_text

FIX = Path(__file__).parent / "fixtures" / "verilatorize"
GLBL = FIX / "glbl.v"
# The spec §6.2 fixture set (Task 14 equivalence-checks every one of these). MMCMVZ (vz_cone.v)
# left it under ruling S28: its trigger crosses an NBA-written register, so it is refused.
# VZCEA joined it under ruling S31(3): 16 fixtures.
MODS = {
    "vz_single.v": "VZSINGLE",
    "vz_multi.v": "VZMULTI",
    "vz_retain.v": "VZRETAIN",
    "vz_nonconst.v": "VZNONCONST",
    "vz_trig.v": "VZTRIG",
    "vz_select.v": "VZSEL",
    "vz_task.v": "VZTASK",
    "vz_shift.v": "VZSHIFT",
    "vz_delay.v": "VZDELAY",
    "vz_async.v": "VZASYNC",
    "vz_gate.v": "BUFVZ",
    "vz_sub.v": "VZSUB",
    "vz_generate.v": "VZGEN",
    "vz_ranges.v": "VZRANGE",
    "vz_ifelse.v": "VZIFELSE",
    # ruling S31(3): an NBA-triggered assign that is never deassigned (accepted, S29(1))
    "vz_cea.v": "VZCEA",
}
# Ruling S18 fixtures: stale reads, real/integer forced regs, helper modules, `output reg`
# ports, no-op deassigns, never-written variables.
S18_MODS = {
    "vz_stale.v": "VZSTALE",
    "vz_rao.v": "VZRAO",
    "vz_real.v": "VZREAL",
    "vz_loopwait.v": "VZLOOPWAIT",
    "vz_initforce.v": "VZINIT",
    "vz_portreg.v": "VZPORTREG",
    "vz_noopdeassign.v": "VZNOOP",
    "vz_constvar.v": "VZCONST",
    "vz_fresh.v": "VZFRESH",
}
ALL = {**MODS, **S18_MODS}


def W(name):  # the X__base declaration, with its Verilator BLKANDNBLK waiver
    return f"/* verilator lint_off BLKANDNBLK */ {name} /* verilator lint_on BLKANDNBLK */"


def _rw(fname):
    return rewrite(analyze(FIX / fname, ALL[fname], GLBL))


@pytest.mark.parametrize("fname", sorted(ALL))
def test_output_is_clean_and_elaborates_in_every_generate_config(fname):
    out = _rw(fname)
    assert out.startswith("// SPDX-License-Identifier: Apache-2.0\n// GENERATED by xut")
    assert out.count("SPDX-License-Identifier") == 1  # the fixture's own line is not repeated
    check_clean(out, ALL[fname], GLBL, generate_configs(FIX / fname, ALL[fname]))


def test_vztrig_golden_fragments():
    out = _rw("vz_trig.v")
    assert (
        f"reg {W('q__base')}; reg [1:0] q__ovr_sel = 2'd0; wire q; wire q__ovr_1; "
        "wire q__ovr_2; wire q__ovr_3;\n"
    ) in out
    assert "    if (gsr_in) q__ovr_sel = 2'd1;\n" in out
    assert "    else if (CLR) q__ovr_sel = 2'd2;\n" in out
    assert "    else if (PRE) q__ovr_sel = 2'd3;\n" in out
    assert (
        "    else begin if (q__ovr_sel != 2'd0) begin q__base = q__active(); "
        "q__ovr_sel = 2'd0; end end\n"
    ) in out
    assert "always @(posedge C) q__base <= D;" in out
    assert (
        "  // xut verilatorize: shadow-register override muxes (spec §6.2)\n"
        "  assign q__ovr_1 = 1'b0;\n"
        "  assign q__ovr_2 = 1'b0;\n"
        "  assign q__ovr_3 = 1'b1;\n"
        "  assign q = (q__ovr_sel == 2'd0) ? q__base : (q__ovr_sel == 2'd1) ? q__ovr_1 : "
        "(q__ovr_sel == 2'd2) ? q__ovr_2 : q__ovr_3;\n"
    ) in out
    # the deassign captures the ACTIVE override expression's value, never the net q (S18)
    assert (
        "  function q__active();\n"
        "    if (q__ovr_sel == 2'd1) q__active = 1'b0;\n"
        "    else if (q__ovr_sel == 2'd2) q__active = 1'b0;\n"
        "    else q__active = 1'b1;\n"
        "  endfunction\nendmodule"
    ) in out
    assert "q__base = q;" not in out


def test_deassign_in_then_arm_keeps_its_else():
    out = _rw("vz_ifelse.v")
    assert (
        "if (C2) begin if (q__ovr_sel != 1'd0) begin q__base = q__active(); "
        "q__ovr_sel = 1'd0; end end\n    else q__ovr_sel = 1'd1;"
    ) in out
    assert "always @(posedge C) q__base <= D;" in out
    assert "assign q = (q__ovr_sel == 1'd0) ? q__base : q__ovr_1;" in out  # one override
    assert "  function q__active();\n    q__active = E;\n  endfunction" in out


def test_delay_and_blocking_form_preserved():
    out = _rw("vz_delay.v")
    assert "q__base <= #100 D;" in out


def test_self_reference_reads_overridden_value():
    out = _rw("vz_shift.v")
    assert "data__base <= {data[2:0], D};" in out


def test_select_writes_renamed():
    out = _rw("vz_select.v")
    assert "v__base[0] <=" in out and "v__base[2:1] <=" in out


def test_task_write_renamed():
    out = _rw("vz_task.v")
    assert "      r__base = val;" in out


def test_both_generate_arms_rewritten():
    out = _rw("vz_generate.v")
    assert out.count("r__base <=") == 2  # posedge arm and negedge arm


def test_packed_range_preserved():
    out = _rw("vz_ranges.v")
    assert "wire [4:1] a;" in out and "wire [0:3] b;" in out and "wire signed [7:0] c;" in out
    assert "wire [4:1] a__ovr_1;" in out and "wire signed [7:0] c__ovr_1;" in out
    assert "function signed [7:0] c__active();" in out and "function [0:3] b__active();" in out
    assert f"reg [4:1] {W('a__base')};" in out and f"reg signed [7:0] {W('c__base')};" in out


def test_missed_rename_is_caught():
    an = analyze(FIX / "vz_generate.v", "VZGEN", GLBL)
    # drop the g_neg arm's write (textually first): only IS_C_INVERTED=1'b1 elaborates it
    an.forced["r"].writes = set(sorted(an.forced["r"].writes, key=lambda w: w.start)[1:])
    with pytest.raises(TransformError, match="IS_C_INVERTED"):  # the failing config is named
        check_clean(rewrite(an), "VZGEN", GLBL, generate_configs(FIX / "vz_generate.v", "VZGEN"))


def test_leftover_procedural_assign_is_caught():
    an = analyze(FIX / "vz_single.v", "VZSINGLE", GLBL)
    an.forced["q"].deassigns = []
    with pytest.raises(TransformError, match="procedural assign/deassign remains"):
        check_clean(rewrite(an), "VZSINGLE", GLBL, [{}])


# ---- ruling S18 --------------------------------------------------------------------------------
def test_stale_reads_substituted():
    out = _rw("vz_stale.v")
    # after `assign r = A;` the read sees the active override's value, typed as r
    assert "begin r__ovr_sel = 1'd1; r__now = A; end\n      x = r__now;" in out
    # after `deassign r;` the read sees r__base, which the deassign just loaded
    assert "r__ovr_sel = 1'd0; end end\n      y = r__base;" in out
    assert "reg r__now;" in out
    out = _rw("vz_rao.v")
    assert "begin r__ovr_sel = 1'd1; r__now = 1'b0; end\n    x = r__now;" in out


def test_read_after_blocking_write_reads_fresh_value():
    out = _rw("vz_fresh.v")
    fresh = "cnt__rd = (cnt__ovr_sel == 1'd0) ? cnt__base : cnt__active();"
    assert "reg [3:0] cnt__rd;" in out and "function [3:0] cnt__active();" in out
    assert "    if (E) cnt__base = cnt + 1;\n" in out  # first read of the block: the net
    assert f"    begin {fresh} y = cnt__rd; end\n" in out
    # the refreshed statement stays one statement: its `else` keeps its `if`
    assert f"    begin {fresh} if (cnt__rd[0]) z = 1'b1;\n    else z = 1'b0; end\n" in out


def test_fresh_read_in_a_loop_header_is_refused(tmp_path):
    src = (FIX / "vz_fresh.v").read_text().replace("    y = cnt;\n", "    while (cnt[3]) y = 0;\n")
    f = _write(tmp_path, "vz_fl.v", src)
    with pytest.raises(TransformError, match="cnt is read in a loop header"):
        rewrite(analyze(f, "VZFRESH", GLBL))


def test_fresh_read_in_an_implicit_sensitivity_block_is_refused():
    # MMCME2_ADV-style: Verilator would re-run the @* block when the override is released
    an = analyze(FIX / "vz_bad_freshcomb.v", "VZFRESHCOMB", GLBL)
    with pytest.raises(TransformError, match="rl: .* implicit sensitivity at line 10"):
        rewrite(an)


def test_no_snapshot_without_stale_reads():
    out = _rw("vz_trig.v")
    assert "__now" not in out


def test_real_forced_reg_is_a_real_variable():
    out = _rw("vz_real.v")
    assert f"real {W('rv__base')}; reg [0:0] rv__ovr_sel = 1'd0; real rv; real rv__ovr_1;" in out
    assert "  assign rv = (rv__ovr_sel == 1'd0) ? rv__base : rv__ovr_1;" in out
    assert "  function real rv__active();\n    rv__active = 1.5;\n  endfunction" in out
    assert "always @(posedge C) rv__base = rv + 1.0;" in out


def test_integer_forced_reg_keeps_signed_32_bits():
    out = _rw("vz_loopwait.v")
    assert (
        f"integer {W('cnt__base')}; reg [0:0] cnt__ovr_sel = 1'd0; wire signed [31:0] cnt;"
    ) in out
    assert "function signed [31:0] cnt__active();" in out
    assert "cnt__base = cnt + 1;" in out


def test_initialisation_force_keeps_the_initial_value():
    out = _rw("vz_initforce.v")
    assert (
        f"reg [3:0] {W('data__base')} = 4'h5; reg [0:0] data__ovr_sel = 1'd0; wire [3:0] data;"
    ) in out
    assert "data__base = data__active();" in out


def test_output_reg_port_becomes_a_net():
    out = _rw("vz_portreg.v")
    assert f"  output  [1:0] Q; reg [1:0] {W('Q__base')}; reg [0:0] Q__ovr_sel = 1'd0; " in out
    assert "wire [1:0] Q;" not in out
    assert "Q__base <= {Q[0], D};" in out


def _helper_blocking(tmp_path):
    """vz_helper.v with its registered stage written by blocking assignments (the NBA form is
    refused, ruling S28)."""
    src = (FIX / "vz_helper.v").read_text().replace("rst_q <= ", "rst_q = ")
    return _write(tmp_path, "vz_helper.v", src)


def test_helper_module_rewritten_in_place(tmp_path):
    f = _helper_blocking(tmp_path)
    an = analyze(f, "VZHELPER", GLBL)
    out = rewrite(an)
    check_clean(out, "VZHELPER", GLBL, [{}])
    core, top = out.split("module VZHELPER ")
    assert f"reg {W('q__base')};" in core and "always @(posedge C) q__base <= D;" in core
    assert "assign q = (q__ovr_sel == 1'd0) ? q__base : q__ovr_1;\n" in core
    assert core.rstrip().endswith("endfunction\nendmodule")
    assert "__ovr" not in top


def test_noop_deassign_becomes_a_null_statement():
    out = _rw("vz_noopdeassign.v")
    assert "    else ;\n" in out and "deassign q" not in out
    assert "__base" not in out  # q is not transformed


# ---- refusals ---------------------------------------------------------------------------------
def _write(tmp_path, name, text):
    f = tmp_path / name
    f.write_text(text)
    return f


@pytest.mark.parametrize(
    "fname,model,reg",
    [
        ("vz_bad_nbacone.v", "VZCE", "q: trigger cone contains NBA-written reg r"),
        ("vz_cone.v", "MMCMVZ", "locked: trigger cone contains NBA-written reg rst_int"),
        (
            "vz_helper.v",
            "VZHELPER",
            "VZHELPER: in helper module VZHELPER_CORE: q: trigger cone contains NBA-written "
            "reg rst_q",
        ),
    ],
)
def test_nba_written_reg_in_trigger_cone_is_refused(fname, model, reg):
    # ruling S28: the forcing block can run from the NBA region (VZCE diverges on Verilator)
    an = analyze(FIX / fname, model, GLBL)
    with pytest.raises(TransformError, match=re.escape(reg)):
        rewrite(an)


def test_nba_cone_without_deassign_is_accepted(tmp_path):
    # no deassign: no blocking capture into X__base, nothing mixed (IDELAYE2 cntvalueout_pre)
    src = (FIX / "vz_bad_nbacone.v").read_text().replace("    else deassign q;\n", "")
    f = _write(tmp_path, "vz_ce_nodeassign.v", src)
    an = analyze(f, "VZCE", GLBL)
    assert an.forced["q"].nba_cone == {"r"}
    check_clean(rewrite(an), "VZCE", GLBL, [{}])


def test_nonconstant_overrides_flag():
    assert analyze(FIX / "vz_nonconst.v", "VZNONCONST", GLBL).nonconstant_overrides
    assert analyze(FIX / "vz_multi.v", "VZMULTI", GLBL).nonconstant_overrides  # `assign r = D`
    assert not analyze(FIX / "vz_trig.v", "VZTRIG", GLBL).nonconstant_overrides


def test_forcing_in_implicit_sensitivity_block_is_refused(tmp_path):
    src = (FIX / "vz_single.v").read_text()
    f = _write(tmp_path, "vz_star.v", re.sub(r"always @\([^)]*\)", "always @*", src, count=1))
    with pytest.raises(TransformError, match="implicit sensitivity"):
        rewrite(analyze(f, "VZSINGLE", GLBL))


def test_override_reading_a_generate_local_constant_is_refused(tmp_path):
    f = _write(
        tmp_path,
        "vz_genlocal.v",
        """// SPDX-License-Identifier: Apache-2.0
`timescale 1ps/1ps
module VZGL (output Q, input C, input D, input R);
  localparam V = 1'b0;
  reg r;
  assign Q = r;
  generate if (1) begin : g
    localparam V = 1'b1;
    always @(R) if (R) assign r = V; else deassign r;
  end endgenerate
  always @(posedge C) r <= D;
endmodule
""",
    )
    with pytest.raises(TransformError, match="reads V, which is declared in an enclosing"):
        rewrite(analyze(f, "VZGL", GLBL))


def test_name_collision_is_refused(tmp_path):
    src = (FIX / "vz_single.v").read_text().replace("  reg q;", "  reg q;\n  wire q__base;")
    f = _write(tmp_path, "vz_clash.v", src)
    with pytest.raises(TransformError, match="q__base is already used"):
        rewrite(analyze(f, "VZSINGLE", GLBL))


def test_non_ascii_model_round_trips(tmp_path):
    src = (FIX / "vz_trig.v").read_bytes().replace(b"several", b"s\xc3\xa9veral \xff")
    f = tmp_path / "vz_trig.v"
    f.write_bytes(src)
    out = rewrite(analyze(f, "VZTRIG", GLBL))
    write_text(tmp_path / "out.v", out)
    raw = (tmp_path / "out.v").read_bytes()
    assert b"s\xc3\xa9veral \xff" in raw and b"q__base <= D;" in raw
    check_clean(out, "VZTRIG", GLBL, [{}])


# ---- container: Verilator and Icarus accept every transformed fixture --------------------------
_no_image = shutil.which("docker") is None or image_digest(SIM_IMAGE) is None


@pytest.mark.container
@pytest.mark.skipif(_no_image, reason="xut-sim image not built")
@pytest.mark.parametrize("fname", sorted(ALL))
def test_verilator_and_icarus_accept_transformed(fname):
    model = ALL[fname]
    work = repo_root() / "build" / "vz-lint" / model
    shutil.rmtree(work, ignore_errors=True)
    work.mkdir(parents=True)
    write_text(work / fname, _rw(fname))
    shutil.copy(GLBL, work / "glbl.v")
    log = work / "lint.log"
    ex = DockerExecutor()
    rc = ex.run(
        ["verilator", "--lint-only", "--timing", "-Wno-fatal", "-Wno-lint", "-Wno-style",
         "-Wno-MULTITOP", fname, "glbl.v"],
        cwd=work, log=log, timeout_s=120,
    )  # fmt: skip
    assert rc == 0, log.read_text()
    rc = ex.run(
        ["iverilog", "-g2012", "-o", "sim.vvp", "-s", model, "-s", "glbl", fname, "glbl.v"],
        cwd=work, log=log, timeout_s=120,
    )  # fmt: skip
    assert rc == 0, log.read_text()


# ---- slow sweep: every analysable UNISIM model, transformed, parses and elaborates ----------
def _errors(log):
    """Icarus error messages without their file:line prefix (lines shift in the rewrite)."""
    return {
        re.sub(r"^\S+?:\d+: ", "", line)
        for line in log.read_text().splitlines()
        if "error" in line and not line.startswith("$ ")
    }


def _with_defaults(path, model, cfg):
    """``path``'s text with the defaults of ``model``'s parameters in ``cfg`` replaced."""
    from xut.verilatorize.analyze import _param_decls, _Source

    src = _Source(path)
    tree = pyslang.syntax.SyntaxTree.fromFile(str(path))
    edits = []
    for name, _, init, _ in _param_decls(tree, model):
        if name in cfg:
            r = init.sourceRange
            edits.append((src.char(r.start.offset), src.char(r.end.offset), cfg[name]))
    assert {n for n in cfg} <= {n for n, *_ in _param_decls(tree, model)}, cfg
    text = src.text
    for a, b, rep in sorted(edits, reverse=True):
        text = text[:a] + rep + text[b:]
    return text


def _lint(ms, model, work, configs):
    """(verilator ok under the default and every generate configuration, icarus ok, icarus
    errors the ORIGINAL model has too) for ``model``'s transformed copy, logging to ``work``."""
    from xut.container import executor_for
    from xut.verilatorize.driver import model_files, vz_dir

    shutil.rmtree(work, ignore_errors=True)
    work.mkdir(parents=True)
    ex = executor_for(ms, work)
    libs = [a for d in ms.search for a in ("-y", ex.guest(d))]
    src, glbl = ex.guest(vz_dir(ms) / f"{model}.v"), ex.guest(ms.glbl)
    vl = ex.run(
        ["verilator", "--lint-only", "--timing", "-Wno-fatal", "-Wno-lint", "-Wno-style",
         "-Wno-MULTITOP", "-y", ex.guest(vz_dir(ms)), *libs, "+libext+.v", src, glbl],
        cwd=work, log=work / "verilator.log", timeout_s=600,
    )  # fmt: skip
    for k, cfg in enumerate((c for c in configs if c), start=1):
        # -G does not reach a model beside glbl (two tops), and a wrapper instance trips
        # Verilator's "tristate in top-level IO" on the FD* models: lint a copy of the
        # transformed model with the parameter defaults set to the configuration instead.
        copy = work / f"cfg{k}" / f"{model}.v"
        copy.parent.mkdir()
        write_text(copy, _with_defaults(vz_dir(ms) / f"{model}.v", model, cfg))
        vl |= ex.run(
            ["verilator", "--lint-only", "--timing", "-Wno-fatal", "-Wno-lint", "-Wno-style",
             "-Wno-MULTITOP", "-y", ex.guest(vz_dir(ms)), *libs, "+libext+.v",
             ex.guest(copy), glbl],
            cwd=work, log=work / f"verilator-cfg{k}.log", timeout_s=600,
        )  # fmt: skip
    iv = ex.run(
        ["iverilog", "-g2012", "-o", "sim.vvp", "-s", model, "-s", "glbl",
         "-y", ex.guest(vz_dir(ms)), *libs, src, glbl],
        cwd=work, log=work / "iverilog.log", timeout_s=600,
    )  # fmt: skip
    if iv == 0:
        return vl == 0, True, False
    orig = ex.guest(model_files(ms)[model])
    ex.run(
        ["iverilog", "-g2012", "-o", "orig.vvp", "-s", model, "-s", "glbl", *libs, orig, glbl],
        cwd=work, log=work / "iverilog-orig.log", timeout_s=600,
    )  # fmt: skip
    new = _errors(work / "iverilog.log")
    return vl == 0, False, bool(new) and new <= _errors(work / "iverilog-orig.log")


# Refused, each for a reason the transform cannot prove it handles:
#   RAMB18E1/RAMB36E1: nested generate conditions (TODO before the bram unit);
#   the rest: a deassigned reg whose trigger cone holds an NBA-written reg (ruling S28).
_NBA_BOTH = [
    "BUFGCE_DIV", "BUFG_GT", "CFGLUT5", "MMCME2_ADV", "MMCME3_ADV", "MMCME4_ADV", "ODDRE1",
    "PLLE2_ADV", "PLLE3_ADV", "PLLE4_ADV", "SRL16E", "SRLC16E", "SRLC32E",
    "RAMB18E1", "RAMB36E1",
]  # fmt: skip
REFUSED = {
    "unisim-2025.2": sorted([*_NBA_BOTH, "MBUFGCE_DIV", "MBUFG_GT", "PLLE4XP_ADV"]),
    "unisim-gh-2020.1": sorted(_NBA_BOTH),
}


@pytest.mark.slow
@pytest.mark.container
@pytest.mark.skipif(_no_image, reason="xut-sim image not built")
@pytest.mark.parametrize("source,n_transformed", [("unisim-2025.2", 27), ("unisim-gh-2020.1", 25)])
def test_sweep_every_transformed_model_lints(source, n_transformed):
    from concurrent.futures import ThreadPoolExecutor

    from xut.modelsrc import model_sources
    from xut.verilatorize.driver import verilatorize

    ms = model_sources().get(source)
    if ms is None:
        pytest.skip(f"model source {source} not available")
    man = verilatorize(ms, jobs=16, progress=lambda _line: None)
    done = sorted(m for m, e in man.models.items() if e.status == "transformed")
    refused = {m: e.reason for m, e in man.models.items() if e.status == "unsupported"}
    assert len(done) == n_transformed, refused
    assert sorted(refused) == REFUSED[source], refused
    for m, why in refused.items():
        assert ("nested generate" if m.startswith("RAMB") else "NBA-written reg") in why, why
    for m in ("FDRE", "FDSE", "FDCE", "FDPE"):
        e = man.models[m]
        assert "glbl.GSR" in e.triggers and len(e.generate_configs) > 1
    root = repo_root() / "build" / "vz-lint-sweep" / source
    with ThreadPoolExecutor(16) as pool:
        res = dict(
            zip(
                done,
                pool.map(lambda m: _lint(ms, m, root / m, man.models[m].generate_configs), done),
                strict=True,
            )
        )
    vl_ok = [m for m, r in res.items() if r[0]]
    iv_ok = [m for m, r in res.items() if r[1]]
    iv_orig = [m for m, r in res.items() if r[2]]
    n_cfg = sum(len(man.models[m].generate_configs or [{}]) for m in done)
    (root / "summary.txt").write_text(
        f"{source}: transformed {len(done)}; verilator lint clean {len(vl_ok)} (every one of "
        f"{n_cfg} configurations); icarus clean "
        f"{len(iv_ok)}; icarus fails as the original does: {iv_orig}\n"
    )
    bad = [f"{m}: verilator={v} icarus={i} (logs {root / m})" for m, (v, i, o) in res.items()
           if not v or not (i or o)]  # fmt: skip
    assert not bad, "\n".join(bad)
    # known Icarus 12 limitation of the model itself: a scalar port redeclared [1:0]
    assert iv_orig == (["OSERDESE1"] if "OSERDESE1" in done else [])


_FRESH_TB = """`timescale 1ps/1ps
module tb;
  reg C = 0, R = 0, E = 0;
  wire [3:0] Q, Y;
  wire Z;
  integer i;
  VZFRESH dut (.Q(Q), .Y(Y), .Z(Z), .C(C), .R(R), .E(E));
  initial begin
    #10;
    for (i = 0; i < 5; i = i + 1) begin
      E = (i != 2); #5 C = 1; #5 $display("OUT %0d Q=%h Y=%h Z=%b", i, Q, Y, Z); C = 0;
    end
    R = 1; #5 C = 1; #5 $display("OUT forced Q=%h Y=%h Z=%b", Q, Y, Z); C = 0;
    R = 0; #5 $display("OUT released Q=%h", Q);
    #5 C = 1; #5 $display("OUT after Q=%h Y=%h Z=%b", Q, Y, Z);
    $finish;
  end
endmodule
"""


@pytest.mark.container
@pytest.mark.skipif(_no_image, reason="xut-sim image not built")
@pytest.mark.parametrize("fname,tb,n", [("vz_fresh.v", _FRESH_TB, 8)])
def test_fresh_reads_match_the_original_on_icarus_and_verilator(fname, tb, n):
    work = repo_root() / "build" / "vz-lint" / f"{ALL[fname]}-sim"
    shutil.rmtree(work, ignore_errors=True)
    (work / "orig").mkdir(parents=True)
    (work / "vz").mkdir()
    shutil.copy(FIX / fname, work / "orig" / "m.v")
    write_text(work / "vz" / "m.v", _rw(fname))
    ex = DockerExecutor()
    out = {}
    for d in ("orig", "vz"):
        (work / d / "tb.v").write_text(tb)
        log = work / d / "run.log"
        cmd = "iverilog -g2012 -o sim.vvp -s tb tb.v m.v && vvp -n sim.vvp"
        assert ex.run(["bash", "-c", cmd], cwd=work / d, log=log, timeout_s=120) == 0
        out[d] = [ln for ln in log.read_text().splitlines() if ln.startswith("OUT ")]
    assert len(out["orig"]) == n and out["vz"] == out["orig"]
    log = work / "vz" / "verilator.log"
    cmd = (
        "verilator --binary --timing -Wno-fatal -Wno-lint -Wno-style --top-module tb "
        "tb.v m.v -o vtb && ./obj_dir/vtb"
    )
    assert ex.run(["bash", "-c", cmd], cwd=work / "vz", log=log, timeout_s=600) == 0
    assert [ln for ln in log.read_text().splitlines() if ln.startswith("OUT ")] == out["orig"]


def _random_tb(model, inputs, outputs):
    """A testbench toggling ``inputs`` (C: a clock) from an LFSR, printing ``outputs``
    between changes (the reviewer's VZCE harness, generalised)."""
    others = [i for i in inputs if i != "C"]
    decl = "".join(f"  reg {i} = 0;\n" for i in inputs)
    decl += "".join(f"  wire [{w - 1}:0] {o};\n" for o, w in outputs.items())
    conns = ", ".join(f".{p}({p})" for p in [*outputs, *inputs])
    fmt = " ".join(f"{p}=%h" for p in [*outputs, *inputs])
    args = ", ".join([*outputs, *inputs])
    drive = " ".join(
        f"if (lfsr[{k + 1}] ^ lfsr[{k + 8}]) {i} = lfsr[{k + 11}];" for k, i in enumerate(others)
    )
    return f"""`timescale 1ps/1ps
module tb;
{decl}  reg [31:0] lfsr = 32'hACE1_1234;
  integer i;
  {model} dut ({conns});
  task step; lfsr = {{lfsr[30:0], lfsr[31]^lfsr[21]^lfsr[1]^lfsr[0]}}; endtask
  initial begin
    for (i = 0; i < 3000; i = i + 1) begin
      step; C = ~C; if (lfsr[3] & lfsr[5]) begin {drive} end
      #2 $display("OUT %0t {fmt}", $time, {args});
      #1 step; if (lfsr[4] & lfsr[9]) begin {drive} end
      #2 $display("OUT %0t {fmt}", $time, {args});
      #5;
    end
    $finish;
  end
endmodule
"""


@pytest.mark.container
@pytest.mark.skipif(_no_image, reason="xut-sim image not built")
@pytest.mark.parametrize(
    "fname,inputs,outputs",
    [
        ("vz_trig.v", ["C", "D", "CLR", "PRE"], {"Q": 1}),
        ("vz_ifelse.v", ["C", "D", "C2", "E"], {"Q": 1}),
        ("vz_select.v", ["C", "D", "R"], {"Q": 3}),
    ],
)
def test_accepted_fixture_matches_original_on_icarus_and_verilator(fname, inputs, outputs):
    """Original on Icarus == transformed on Icarus == transformed on Verilator, under random
    stimulus that includes releases coincident with clock edges (ruling S28)."""
    model = ALL[fname]
    work = repo_root() / "build" / "vz-lint" / f"{model}-random"
    shutil.rmtree(work, ignore_errors=True)
    tb = _random_tb(model, inputs, outputs)
    runs = {
        "orig": (lambda d: shutil.copy(FIX / fname, d / "m.v"), "iverilog"),
        "vz": (lambda d: write_text(d / "m.v", _rw(fname)), "iverilog"),
        "vzv": (lambda d: write_text(d / "m.v", _rw(fname)), "verilator"),
    }
    ex = DockerExecutor()
    out = {}
    for name, (put, sim) in runs.items():
        d = work / name
        d.mkdir(parents=True)
        put(d)
        (d / "tb.v").write_text(tb)
        shutil.copy(GLBL, d / "glbl.v")
        cmd = (
            "iverilog -g2012 -o sim.vvp -s tb -s glbl tb.v m.v glbl.v && vvp -n sim.vvp"
            if sim == "iverilog"
            else "verilator --binary --timing -Wno-fatal -Wno-lint -Wno-style -Wno-MULTITOP "
            "tb.v m.v glbl.v -o vtb && ./obj_dir/vtb"
        )
        log = d / "run.log"
        assert ex.run(["bash", "-c", cmd], cwd=d, log=log, timeout_s=600) == 0, log.read_text()
        out[name] = [ln for ln in log.read_text().splitlines() if ln.startswith("OUT ")]
    assert len(out["orig"]) == 6000
    assert out["vz"] == out["orig"]
    assert out["vzv"] == out["orig"]
