# SPDX-License-Identifier: Apache-2.0
"""xut.unitkit: the shared pieces of a work unit's metadata and guards (ruling S53)."""

import pytest
import yaml
from test_runner_base import FIX, TOY_ENTRY

from xut import unitkit
from xut.testspec import DECLARED_RUNNERS, discover


def test_runners_default_yes_and_reasons_for_the_rest():
    runs, reasons = unitkit.runners(hw=unitkit.HW_GSR, python=unitkit.SV_PY)
    assert list(runs) == list(DECLARED_RUNNERS)
    assert runs["hw"] == "unsupported" and runs["python"] == "no" and runs["xsim"] == "yes"
    assert reasons == {"hw": unitkit.HW_GSR[1], "python": unitkit.SV_PY[1]}


def test_class_bins_come_from_the_catalog():
    assert unitkit.class_bins(TOY_ENTRY, "D") == ["port:D", "port:D:0", "port:D:1"]
    assert unitkit.class_bins(TOY_ENTRY, "D", "1") == ["port:D", "port:D:1"]
    assert unitkit.class_bins(TOY_ENTRY, "C") == ["port:C", "port:C:edge"]


def test_entry_requires_gaps_and_dedupes_exercises():
    with pytest.raises(ValueError, match="misses"):
        unitkit.entry("7series", "TOYFF", "L1", "x", "vector", "vectors/gen.py:x", [], gaps=[])
    e = unitkit.entry(
        "7series",
        "TOYFF",
        "L1",
        "x",
        "vector",
        "vectors/gen.py:x",
        ["port:D"] * 2,
        gaps=["g"],
        declared=unitkit.runners(hw=unitkit.HW_REJ),
    )
    assert e["id"] == "7series.TOYFF.L1.x" and e["exercises"] == ["port:D"]
    assert e["unsupported_reasons"] == {"hw": unitkit.HW_REJ[1]}


def test_dump_test_yaml_writes_no_aliases_and_quoted_yes():
    shared = ["rtl"]
    text = unitkit.dump_test_yaml({"a": shared, "b": shared, "c": "yes"}, "x/y.py")
    assert text.startswith("# SPDX-License-Identifier: Apache-2.0\n# GENERATED by x/y.py")
    assert "&id" not in text and "*id" not in text
    assert yaml.safe_load(text)["c"] == "yes"


def test_render_readme_has_every_template_section(tmp_path):
    e = unitkit.entry("7series", "TOYFF", "L1", "x", "vector", "vectors/gen.py:x", [], gaps=["g"])
    text = unitkit.render_readme(
        prim="TOYFF",
        title="toy",
        reference="ref",
        overview="ov",
        tests=[(e, "why")],
        oracle=["model"],
        known_gaps=["timing"],
        root=tmp_path,
    )
    for section in (
        "## Overview",
        "## Tests",
        "## Why each test",
        "## Oracle",
        "## Known gaps",
        "## Runner support",
        "## Related tests",
        "## How to run",
    ):
        assert section in text
    assert 'flock "$XDG_RUNTIME_DIR/xut-heavy.lock"' in text


def test_vector_reach_replays_like_the_python_runner(toy):
    case = next(c for c in discover(FIX) if c.id == "7series.TOYFF.L1.capture")
    reach = unitkit.vector_reach(case, FIX)
    assert [c.cfg for c in reach] == ["init0", "init1"]
    assert all(c.pure for c in reach)  # ToyDff tags every bit doc:1
    assert "claim:TOYFF.C1" in set().union(*(c.bins for c in reach))
    reject = next(c for c in discover(FIX) if c.id == "7series.TOYFF.L0.reject")
    assert unitkit.vector_reach(reject, FIX) == []  # reject configurations are not replayed


def test_documented_is_false_for_any_inferred_bit():
    assert unitkit._documented({"S0": {"Q": "doc:1"}})
    assert not unitkit._documented({"S0": {"Q": "doc:1,inferred:x"}})


def test_unit_guards_parametrizes_over_the_units_primitives():
    unit = unitkit.Unit(
        "toy", "7series", FIX, FIX / "tests/7series/register", ("TOYFF",), dict, dict
    )
    guards = type("TestToy", (unitkit.UnitGuards,), {"unit": unit})()
    seen = []

    class Meta:
        fixturenames = ("prim",)

        def parametrize(self, name, values):
            seen.append((name, tuple(values)))

    guards.pytest_generate_tests(Meta())
    assert seen == [("prim", ("TOYFF",))]
    assert not unitkit.UnitGuards.__name__.startswith("Test")


def test_mutant_fails_on_a_crediting_configuration(toy):
    from test_golden import ToyDff

    class NoCapture(ToyDff):  # breaks TOYFF.C1: never captures D
        def clock_edge(self, port, rising):
            pass

    case = next(c for c in discover(FIX) if c.id == "7series.TOYFF.L1.capture")
    assert unitkit.mutant_fails(case, FIX, "TOYFF.C1", NoCapture) is True
    assert unitkit.mutant_fails(case, FIX, "TOYFF.C1", ToyDff) is False  # golden: no mismatch
    assert unitkit.mutant_fails(case, FIX, "TOYFF.C9", NoCapture) is None  # nothing credits it


def test_an_event_mutant_must_fail_every_crediting_configuration(toy):
    """Ruling S55a: ``every=True`` (an event claim) needs the mutant caught in each
    configuration that credits the claim; one catching configuration is not enough."""
    from test_golden import ToyDff

    from xut_models.base import bit_attr

    class CapturesOnlyFromInit1(ToyDff):  # breaks C1 in init0 only
        def clock_edge(self, port, rising):
            if bit_attr(self.attrs.get("INIT", 0)) == 1:
                super().clock_edge(port, rising)

    case = next(c for c in discover(FIX) if c.id == "7series.TOYFF.L1.capture")
    assert unitkit.mutant_fails(case, FIX, "TOYFF.C1", CapturesOnlyFromInit1) is True
    assert unitkit.mutant_fails(case, FIX, "TOYFF.C1", CapturesOnlyFromInit1, every=True) is False
    assert unitkit.Mutant(ToyDff).event is False  # a read claim unless marked


def test_doc_mismatches_counts_documented_bits_over_a_vector_test(toy):
    from test_golden import ToyDff

    class NoCapture(ToyDff):
        def clock_edge(self, port, rising):
            pass

    case = next(c for c in discover(FIX) if c.id == "7series.TOYFF.L1.capture")
    assert unitkit.doc_mismatches(case, FIX, ToyDff) == 0
    # init0 keeps Q=0 where D=1 was captured, init1 keeps Q=1 where D=0 was
    assert unitkit.doc_mismatches(case, FIX, NoCapture) > 0


def test_cases_selects_one_primitive():
    ids = {c.id for c in unitkit.cases(FIX, "7series", "TOYFF")}
    assert "7series.TOYFF.L1.capture" in ids
    assert all(".TOYFF." in i for i in ids)
    assert unitkit.cases(FIX, "7series", "NOSUCH") == []


def test_doc_mismatch_ignores_inferred_bits():
    from xut.formats.xtr import Trace

    want, got = Trace({"runner": "python"}), Trace({"runner": "x"})
    want.add("S0", {"Q": "10"}, {"Q": "inferred:x,doc:1"})  # per-bit tags, LSB first
    got.add("S0", {"Q": "11"})
    assert not unitkit._doc_mismatch(want, got)
    got2 = Trace({"runner": "x"})
    got2.add("S0", {"Q": "00"})
    assert unitkit._doc_mismatch(want, got2)
