# SPDX-License-Identifier: Apache-2.0
import dataclasses
import json
import shutil
from pathlib import Path

import pytest
from click.testing import CliRunner

from xut import portability
from xut.catalog.unisim import HdlModule, HdlParam, HdlPort
from xut.cli import main
from xut.modelsrc import ModelSource
from xut.portability import (
    Row,
    classify,
    configurations,
    failure,
    flipped,
    parse,
    render,
    smoke_top,
)
from xut.verilatorize.driver import ModelEntry

FIX = Path(__file__).parent / "fixtures" / "verilatorize"

TOY = HdlModule(
    "TOY",
    Path("TOY.v"),
    ports=[
        HdlPort("D", "input", 4),
        HdlPort("C", "input", 1),
        HdlPort("Q", "output", 1),
        HdlPort("IO", "inout", 2),
    ],
    params=[HdlParam("INIT", "bits", 1, "1'b0")],
)


def test_smoke_top_ties_inputs_low_and_leaves_outputs_and_inouts_as_wires():
    text = smoke_top(TOY)
    assert text.startswith(
        "// SPDX-License-Identifier: Apache-2.0\n// GENERATED by xut portability"
    )
    assert "`timescale 1ps / 1ps\nmodule xut_smoke;\n" in text
    assert "  reg  [3:0] i_D = 0;\n  reg  [0:0] i_C = 0;\n" in text
    assert "  wire [0:0] o_Q;\n  wire [1:0] io_IO;\n" in text
    assert "  TOY dut (.D(i_D), .C(i_C), .Q(o_Q), .IO(io_IO));\n" in text
    assert '  initial begin #200000; $display("XUT_SMOKE_OK"); $finish; end\nendmodule\n' in text


def test_smoke_top_passes_overrides_as_parameters():
    text = smoke_top(TOY, {"INIT": "1'b1", "A_STR": '"X"'})
    assert '  TOY #(.A_STR("X"), .INIT(1\'b1)) dut (' in text


@pytest.mark.parametrize(
    ("log", "want"),
    [
        (
            "%Error-UNSUPPORTED: /m/X.v:10:1: Unsupported: Verilog 1995 UDP Tables. "
            "Use --bbox-unsup to ignore tables.",
            "udp",
        ),
        ("%Error-UNSUPPORTED: /m/STARTUPE2.v:40:3: Unsupported: tri1 nets", "tri0-tri1"),
        ("/m/X.v:12: sorry: real variables are not supported here", "real"),
        ("/m/GTXE2_CHANNEL.v:99: error: Unknown module type: SIP_GTXE2_CHANNEL", "secureip"),
        ("%Error: /m/E.v:1:1: file is encrypted (`pragma protect)", "secureip"),
        ("%Error-UNSUPPORTED: /m/S.v:5: Unsupported: Strength specifier", "strength"),
        ("%Error-UNSUPPORTED: /m/D.v:5: Unsupported: Verilog 1995 deassign", "deassign"),
        ("xut-smoke: build exit 0\nxut-smoke: timeout (124)", "timeout"),
        ("%Error: /m/X.v:3:5: syntax error, unexpected IDENTIFIER", "other"),
        ("Error: [Unisim MMCME2_ADV-1] CLKIN1_PERIOD is not set", "other"),
    ],
)
def test_classify(log, want):
    assert classify(log) == want


def test_classify_ignores_warnings_and_non_error_lines():
    log = "%Warning-REALCVT: /m/X.v:1: real converted\nINFO: using a real clock\n%Error: boom"
    assert classify(log) == "other"
    assert failure(log, 1) == "other: %Error: boom"


def test_failure_without_an_error_line_names_the_exit():
    assert failure("xut-smoke: build exit 0\nxut-smoke: run exit 0\n", 0) == (
        "other: exit 0, no XUT_SMOKE_OK"
    )
    assert failure("", None) == "other: the script did not finish"


@pytest.mark.parametrize(
    ("param", "want"),
    [
        (HdlParam("IS_C_INVERTED", "bits", 1, "1'b0"), "1'b1"),
        (HdlParam("IS_C_INVERTED", "bits", 1, "1'b1"), "1'b0"),
        (HdlParam("IS_OPMODE_INVERTED", "bits", 7, "7'b0000000"), "7'b1111111"),
        (HdlParam("IS_A_INVERTED", "bits", 4, "4'h5"), "4'b1010"),
        (HdlParam("IS_X_INVERTED", "integer", None, 0), "1"),
        (HdlParam("IS_X_INVERTED", "bits", 1, "1'bx"), None),
        (HdlParam("IS_X_INVERTED", "string", None, "FALSE"), None),
    ],
)
def test_flipped(param, want):
    assert flipped(param) == want


def test_configurations_add_generate_configs_and_each_inversion(tmp_path):
    f = tmp_path / "INV.v"
    f.write_text(
        "// SPDX-License-Identifier: Apache-2.0\n"
        "module INV #(parameter [0:0] IS_C_INVERTED = 1'b0, parameter [0:0] IS_D_INVERTED "
        '= 1\'b0, parameter MODE = "A") (output Q, input C, input D);\n'
        '  generate if (MODE == "B") begin : g assign Q = D; end else begin : h assign Q = C;'
        " end endgenerate\nendmodule\n"
    )
    from xut.catalog.unisim import parse_module

    cfgs, notes = configurations(f, parse_module(f, "INV"))
    assert cfgs == [{}, {"MODE": '"B"'}, {"IS_C_INVERTED": "1'b1"}, {"IS_D_INVERTED": "1'b1"}]
    assert notes == []


ROWS = [
    Row("FDRE", "yes", "yes", "transformed", "pass", ["glbl.GSR", "CE", "R"], [], ""),
    Row(
        "XADC",
        "yes",
        "no",
        "unchanged",
        "—",
        [],
        [],
        "verilator: real: %Error: x | y \\ z [default]",
    ),
    Row("IBUFDS", "yes", "no: verilatorize: IBUFDS: a z-compare | on I_in", "unsupported", "—"),
    Row(
        "BUFGMUX",
        "yes",
        "yes",
        "unchanged (gated: BUFGCTRL)",
        "pass",
        [],
        ["CLK"],
        "note: no generate configurations",
    ),
]


def _meta():
    return {
        "generated": "2026-09-26T20:00Z",
        "head": "abc1234",
        "image": "xut-sim:1",
        "digest": "sha256:d",
    }


def test_render_layout():
    md = render({"unisim-2025.2": ROWS}, _meta())
    assert md.startswith(
        "<!-- GENERATED by xut portability — do not edit -->\n# UNISIM portability\n"
    )
    assert (
        "Generated by `xut portability` on 2026-09-26T20:00Z at abc1234. Container xut-sim:1 "
        "sha256:d." in md
    )
    assert "## unisim-2025.2\n\n| simulator | yes | no |\n|---|---|---|\n" in md
    assert "| iverilog | 4 | 0 |\n| verilator | 2 | 2 |\n" in md
    assert "| FDRE | yes | yes | transformed | pass | glbl.GSR, CE, R | — |  |\n" in md
    assert (
        "| XADC | yes | no | unchanged | — | — | — | verilator: real: %Error: x \\| y \\\\ z" in md
    )


def test_render_parse_round_trip():
    table = {"unisim-2025.2": ROWS, "unisim-gh-2020.1": ROWS[:2]}
    md = render(table, {**_meta(), "sources": {"unisim-2025.2": {
        "generated": "g", "head": "h", "models": 4, "configurations": 9, "models_glob": None,
    }}})  # fmt: skip
    got = parse(md)
    assert list(got) == ["unisim-2025.2", "unisim-gh-2020.1"]
    for ms, rows in table.items():
        assert got[ms] == {r.model: r for r in rows}


def test_parse_refuses_a_malformed_row():
    md = render({"s": ROWS[:1]}, _meta()).replace("| pass |", "|")
    with pytest.raises(portability.PortabilityError, match="8 cells"):
        parse(md)


def test_row_gated_and_why():
    assert ROWS[0].gated and ROWS[3].gated and not ROWS[1].gated and not ROWS[2].gated
    assert ROWS[1].why("verilator") == "real: %Error: x | y \\ z [default]"
    assert ROWS[2].why("verilator") == "verilatorize: IBUFDS: a z-compare | on I_in"


def _entry(**kw) -> ModelEntry:
    return ModelEntry(kw.pop("status", "transformed"), "sha", **kw)


@pytest.mark.parametrize(
    ("entry", "gate", "vz", "equiv"),
    [
        (_entry(equiv={"default": "pass", "INIT=1'b1": "pass"}), None, "transformed", "pass"),
        (_entry(), None, "transformed", "—"),
        (
            _entry(
                equiv={"default": "pass", "A=1": "fail"}, equiv_reason={"A=1": "2 mismatch(es)"}
            ),
            None,
            "transformed",
            "fail",
        ),
        (_entry(status="unchanged"), None, "unchanged", "—"),
        (
            _entry(status="unchanged", depends_on_transformed=["C"], equiv={"default": "error"}),
            None,
            "unchanged (gated: C)",
            "error",
        ),
        (
            _entry(status="unsupported", reason="X: nested generate\nmore"),
            "no: verilatorize: X: nested generate",
            "unsupported",
            "—",
        ),
        (
            _entry(status="unchanged", depends_on_unsupported=["IBUFDS"]),
            "no: blocked by refused dependency IBUFDS",
            "unchanged",
            "—",
        ),
        (
            _entry(depends_on_unsupported=["MMCME3_ADV"]),
            "no: blocked by refused dependency MMCME3_ADV",
            "transformed",
            "blocked",
        ),
    ],
)
def test_manifest_cells(entry, gate, vz, equiv):
    assert portability._gate(entry) == gate
    assert portability._vz_cell(entry) == vz
    assert portability._equiv(entry)[0] == equiv


def test_equiv_reason_names_the_first_failing_configuration():
    e = _entry(equiv={"default": "pass", "A=1": "fail"}, equiv_reason={"A=1": "2 mismatch(es)"})
    assert portability._equiv(e)[1] == "equiv: fail [A=1] (1 of 2): 2 mismatch(es)"


def _write_result(root: Path, ms: str, rows: list[Row], glob: str | None = None) -> None:
    doc = {
        "model_source": ms, **_meta(), "models_glob": glob, "models": len(rows),
        "configurations": 2 * len(rows), "rows": [dataclasses.asdict(r) for r in rows],
    }  # fmt: skip
    d = root / "build" / "portability" / ("partial" if glob else "")
    d.mkdir(parents=True, exist_ok=True)
    (d / f"{ms}.json").write_text(json.dumps(doc))


def test_load_results_reads_full_runs_only(tmp_path):
    _write_result(tmp_path, "unisim-2025.2", ROWS)
    _write_result(tmp_path, "unisim-gh-2020.1", ROWS[:1], glob="FD*")  # partial/: ignored
    rows, meta = portability.load_results(tmp_path)
    assert list(rows) == ["unisim-2025.2"] and rows["unisim-2025.2"] == ROWS
    assert meta["head"] == "abc1234" and meta["sources"]["unisim-2025.2"]["configurations"] == 8


def test_status_generate_also_writes_portability_when_results_exist(tmp_path, monkeypatch):
    (tmp_path / "status" / "7series").mkdir(parents=True)
    (tmp_path / "log").mkdir()
    monkeypatch.setattr("xut.paths.repo_root", lambda start=None: tmp_path)
    monkeypatch.setattr("xut.status.current_branch", lambda: "main")
    monkeypatch.setattr("xut.workunits.load_units", lambda root: {})
    monkeypatch.setattr("xut.workunits.load_family", lambda root: "7series")
    r = CliRunner().invoke(main, ["status", "generate"])
    assert r.exit_code == 0, r.output
    assert not (tmp_path / "status" / "PORTABILITY.md").exists()
    _write_result(tmp_path, "unisim-2025.2", ROWS)
    r = CliRunner().invoke(main, ["status", "generate"])
    assert r.exit_code == 0 and "PORTABILITY.md" in r.output, r.output
    got = parse((tmp_path / "status" / "PORTABILITY.md").read_text())
    assert got == {"unisim-2025.2": {r.model: r for r in ROWS}}


def test_portability_write_refuses_off_main(monkeypatch):
    monkeypatch.setattr("xut.status.current_branch", lambda: "infra/verilatorize")
    r = CliRunner().invoke(main, ["portability", "--write"])
    assert r.exit_code != 0 and "only main regenerates it" in r.output
    r = CliRunner().invoke(main, ["portability", "--write", "--force", "--models", "FD*"])
    assert r.exit_code != 0 and "--write needs a full run" in r.output


# --- the container run on the Task 12 fixture model source ------------------------------------

SIPUSER = """\
// SPDX-License-Identifier: Apache-2.0
module SIPUSER (output O, input I);
  SIP_NOSUCH u (.O(O), .I(I));
endmodule
"""
STOPPER = """\
// SPDX-License-Identifier: Apache-2.0
`timescale 1ps / 1ps
module STOPPER #(parameter [0:0] IS_C_INVERTED = 1'b0) (output O, input C);
  assign O = C ^ IS_C_INVERTED;
  initial if (IS_C_INVERTED) begin
    #1000 $display("Error: [Unisim STOPPER-1] IS_C_INVERTED=1 is not supported");
    $finish;
  end
endmodule
"""
BLOCKED = """\
// SPDX-License-Identifier: Apache-2.0
module BLOCKED (output [1:0] Q, input C, input [1:0] D, input S);
  VZBADSEL u (.Q(Q), .C(C), .D(D), .S(S));
endmodule
"""


@pytest.fixture
def fixture_source(tmp_path):
    src = tmp_path / "src"
    uni = src / "unisims"
    uni.mkdir(parents=True)
    shutil.copy(FIX / "glbl.v", src / "glbl.v")
    for f, model in (
        ("vz_trig.v", "VZTRIG"),
        ("vz_parent.v", "VZPARENT"),
        ("vz_child.v", "VZCHILD"),
        ("vz_bad_select.v", "VZBADSEL"),
    ):
        shutil.copy(FIX / f, uni / f"{model}.v")
    for model, text in (("SIPUSER", SIPUSER), ("STOPPER", STOPPER), ("BLOCKED", BLOCKED)):
        (uni / f"{model}.v").write_text(text)
    (uni / "PLAIN.v").write_text(
        "// SPDX-License-Identifier: Apache-2.0\nmodule PLAIN (output O, input I);\n"
        "  assign O = I;\nendmodule\n"
    )
    return ModelSource("test-src", src)


@pytest.mark.container
def test_run_smoke_on_the_fixture_model_source(tmp_path, fixture_source):
    root = tmp_path / "root"
    root.mkdir()
    lines: list[str] = []
    rows = portability.run_smoke(fixture_source, jobs=8, root=root, progress=lines.append)
    got = {r.model: r for r in rows}
    assert sorted(got) == sorted(p.stem for p in fixture_source.unisims.glob("*.v"))
    assert (got["VZTRIG"].iverilog, got["VZTRIG"].verilator) == ("yes", "yes")
    assert (got["VZTRIG"].verilatorize, got["VZTRIG"].equiv) == ("transformed", "pass")
    assert got["VZTRIG"].triggers == ["CLR", "PRE", "glbl.GSR"]
    assert got["PLAIN"] == Row("PLAIN", "yes", "yes", "unchanged", "—")
    assert got["VZPARENT"].verilatorize == "unchanged (gated: VZCHILD)"
    assert (got["VZPARENT"].equiv, got["VZPARENT"].verilator) == ("pass", "yes")
    assert got["VZBADSEL"].verilator.startswith("no: verilatorize: ")
    # a procedural assign to a bit select: pyslang cannot read its ports, so no smoke top
    assert got["VZBADSEL"].iverilog == "no"
    assert got["VZBADSEL"].reason.startswith("iverilog: other: smoke: cannot read its ports: 1 ")
    assert got["BLOCKED"].verilator == "no: blocked by refused dependency VZBADSEL"
    sip = got["SIPUSER"]
    assert (sip.iverilog, sip.verilator) == ("no", "no")
    assert "iverilog: secureip: " in sip.reason and "verilator: secureip: " in sip.reason
    stop = got["STOPPER"]
    assert (stop.iverilog, stop.verilator) == ("no", "no"), stop
    assert "iverilog: other: Error: [Unisim STOPPER-1]" in stop.reason
    assert stop.reason.split("; ")[0].endswith("[IS_C_INVERTED=1'b1]"), stop.reason
    # the result file and the progress lines
    doc = json.loads((root / "build/portability/test-src.json").read_text())
    assert [r["model"] for r in doc["rows"]] == sorted(got)
    assert doc["configurations"] == 8  # STOPPER has 2 (IS_C_INVERTED flipped), VZBADSEL 0
    smoke = [ln for ln in lines if ln.startswith("progress: done=")]
    total = int(smoke[0].split("total=")[1].split()[0])
    assert smoke[-1].startswith(f"progress: done={total} total={total} ")
    assert not any(ln.startswith("progress: done=") for ln in lines[: lines.index(smoke[0])])
    work = root / "build/portability/test-src"
    assert (work / "VZTRIG/default/smoke.v").is_file()
    assert (work / "VZTRIG/default/verilator.rc").read_text().strip() == "0"
    assert not (work / "VZTRIG/default/obj").exists()  # removed after the run
    assert not (work / "VZBADSEL/default/verilator.sh").exists()  # refused: never built
    assert parse(render({"test-src": rows}, _meta()))["test-src"] == got
