# SPDX-License-Identifier: Apache-2.0
from pathlib import Path

import yaml
from xut.catalog.build import build_all
from xut.catalog.model import load_entry
from xut.catalog.portclass import default_class

FIX = Path(__file__).parent / "fixtures"


def _toy_models(tmp_path):
    u = tmp_path / "unisims"
    u.mkdir()
    (u / "TOYFF.v").write_text(
        'module TOYFF #(parameter [0:0] INIT = 1\'b0, parameter MODE = "FAST", '
        "parameter [0:0] EXTRA = 1'b0)(output Q, input C, input D, output [15:0] DO);\n"
        "endmodule\n"
    )
    r = tmp_path / "retarget"
    r.mkdir()
    (r / "TOYLUT.v").write_text("module TOYLUT(output O, input I0); endmodule\n")
    return [u, r]


def test_build_writes_yaml_and_reports_mismatch(tmp_path):
    out = tmp_path / "catalog"
    report = build_all(
        FIX / "ug953_toy.txt",
        ["TOYFF", "TOYLUT", "GHOST"],
        out,
        _toy_models(tmp_path),
        family="7series",
    )
    ff = yaml.safe_load((out / "TOYFF.yaml").read_text())
    assert ff["group"] == "REGISTER"
    assert [p["name"] for p in ff["ports"]] == ["Q", "C", "D", "DO"]
    assert {a["name"]: a["default"] for a in ff["attributes"]}["MODE"] == "FAST"
    # EXTRA is in UNISIM but not in UG953 table -> reported, still present
    assert any("TOYFF" in line and "EXTRA" in line for line in report)
    lut = yaml.safe_load((out / "TOYLUT.yaml").read_text())
    assert lut["model"]["library"] == "retarget"
    # GHOST: documented name with no model and no section -> reported, not crash
    assert any("GHOST" in line for line in report)


def test_overrides_merge(tmp_path):
    out = tmp_path / "catalog" / "7series"
    build_all(FIX / "ug953_toy.txt", ["TOYFF"], out, _toy_models(tmp_path), family="7series")
    (out / "TOYFF.overrides.yaml").write_text(
        yaml.safe_dump(
            {
                "ports": {"D": {"cls": "async"}},
                "claims": [
                    {"id": "TOYFF.C1", "text": "Q follows D", "page": 10, "provenance": "doc:10"}
                ],
            }
        )
    )
    e = load_entry("7series", "TOYFF", tmp_path)
    assert {p["name"]: p["cls"] for p in e.ports}["D"] == "async"
    assert e.claims[0]["id"] == "TOYFF.C1"


def test_default_port_classes():
    assert default_class("FDRE", "C", "input") == "clock"
    assert default_class("FDCE", "CLR", "input") == "async"
    assert default_class("LDCE", "G", "input") == "gate"
    assert default_class("IOBUF", "IO", "inout") == "inout"
    assert default_class("MMCME2_ADV", "CLKOUT0", "output") == "clock_out"
    assert default_class("MMCME2_ADV", "LOCKED", "output") == "data"
    assert default_class("MMCME2_ADV", "DADDR", "input") == "drp"
    assert default_class("FDRE", "D", "input") == "data"
    assert default_class("IBUF", "I", "input") == "pad"
    assert default_class("BUFGCTRL", "I0", "input") == "clock"
    assert default_class("LUT2", "I0", "input") == "data"


def test_allowed_values_unquoted_like_defaults(tmp_path):
    out = tmp_path / "catalog"
    build_all(FIX / "ug953_toy.txt", ["TOYFF"], out, _toy_models(tmp_path), family="7series")
    ff = yaml.safe_load((out / "TOYFF.yaml").read_text())
    mode = {a["name"]: a for a in ff["attributes"]}["MODE"]
    assert mode["allowed"] == ["FAST", "SLOW"] and mode["default"] in mode["allowed"]
    assert (
        (out / "TOYFF.yaml")
        .read_text()
        .startswith(
            "# SPDX-License-Identifier: Apache-2.0\n"
            "# GENERATED by xut catalog build — edit TOYFF.overrides.yaml instead\n"
        )
    )


def test_build_takes_family_from_caller(tmp_path):
    out = tmp_path / "catalog" / "fam9"
    build_all(FIX / "ug953_toy.txt", ["TOYFF"], out, _toy_models(tmp_path), family="fam9")
    assert yaml.safe_load((out / "TOYFF.yaml").read_text())["family"] == "fam9"


def test_rebuild_is_deterministic(tmp_path):
    out = tmp_path / "catalog"
    models = _toy_models(tmp_path)
    build_all(FIX / "ug953_toy.txt", ["TOYFF", "TOYLUT"], out, models, family="7series")
    first = {p.name: p.read_text() for p in out.iterdir()}
    build_all(FIX / "ug953_toy.txt", ["TOYFF", "TOYLUT"], out, models, family="7series")
    assert first == {p.name: p.read_text() for p in out.iterdir()}


def test_suspicious_doc_values_are_reported():
    from xut.catalog.build import value_issues
    from xut.catalog.ug953 import DocSection

    sec = DocSection("TOYX", "", "G", "S", 1)
    sec.attributes = {
        "OK": {"type": "STRING", "allowed": ['"A"', '"B"'], "default": '"A"'},
        "BAD": {"type": "STRING", "allowed": ['"A" "B"'], "default": '"A"'},
        "EMPTY": {"type": "STRING", "allowed": [], "default": ""},
        "BOOL": {"type": "BOOLEAN", "allowed": ['"X" FALSE', "TRUE"], "default": "FALSE"},
    }
    lines = value_issues("TOYX", sec)
    assert len(lines) == 3 and not any(" OK " in x for x in lines)


def test_overrides_are_validated(tmp_path):
    import jsonschema
    import pytest

    out = tmp_path / "catalog" / "7series"
    build_all(FIX / "ug953_toy.txt", ["TOYFF"], out, _toy_models(tmp_path), family="7series")
    ov = out / "TOYFF.overrides.yaml"
    ov.write_text(yaml.safe_dump({"ports": {"D": {"cls": "bogus"}}}))
    with pytest.raises(jsonschema.ValidationError):
        load_entry("7series", "TOYFF", tmp_path)
    ov.write_text(yaml.safe_dump({"ports": {"NOPE": {"cls": "data"}}}))
    with pytest.raises(KeyError):
        load_entry("7series", "TOYFF", tmp_path)


def test_async_controls_follow_spec_intent():
    for p in ("S0", "S1", "CE0", "CE1", "IGNORE0", "IGNORE1"):
        assert default_class("BUFGCTRL", p, "input") == "async", p
    # only BUFGCTRL: ISERDESE2 CE1 is an ordinary enable like CE2
    assert default_class("ISERDESE2", "CE1", "input") == "data"
    assert default_class("ISERDESE2", "CE2", "input") == "data"
    for prim in ("BUFGMUX", "BUFGMUX_1", "BUFGMUX_CTRL"):
        assert default_class(prim, "S", "input") == "async", prim
    for prim in ("BUFGCE", "BUFGCE_1", "BUFHCE", "BUFMRCE", "BUFR"):
        assert default_class(prim, "CE", "input") == "async", prim
    assert default_class("IDELAYCTRL", "RST", "input") == "async"
    for prim in ("XADC", "IN_FIFO", "OUT_FIFO"):
        assert default_class(prim, "RESET", "input") == "async", prim
    assert default_class("FDRE", "CE", "input") == "data"
    assert default_class("RAMB36E1", "RSTRAMB", "input") == "data"


def test_srtype_dependent_classes_are_noted():
    from xut.catalog.portclass import class_note

    for prim in ("IDDR", "IDDR_2CLK", "ODDR"):
        for p in ("S", "R"):
            assert default_class(prim, p, "input") == "data"
            assert "SRTYPE" in class_note(prim, p)
    assert class_note("FDRE", "R") is None


def test_value_issues_catch_duplicates_and_missing_default():
    from types import SimpleNamespace

    from xut.catalog.build import value_issues
    from xut.catalog.ug953 import DocSection

    sec = DocSection("TOYX", "", "G", "S", 1)
    sec.attributes = {
        "DUP": {"type": "STRING", "allowed": ['"A"', '"B"', '"A"'], "default": ""},
        "MISS": {"type": "STRING", "allowed": ['"TRUE"'], "default": ""},
        "NUM": {"type": "DECIMAL", "allowed": ["1", "2"], "default": "1"},
        "RANGE": {"type": "DECIMAL", "allowed": ["1 to 128"], "default": "1"},
        "OK": {"type": "BOOLEAN", "allowed": ["FALSE", "TRUE"], "default": "FALSE"},
    }
    P = SimpleNamespace
    model = SimpleNamespace(
        params=[
            P(name="DUP", default="A"),
            P(name="MISS", default="7SERIES"),
            P(name="NUM", default=4),
            P(name="RANGE", default=200),
            P(name="OK", default="FALSE"),
        ]
    )
    lines = value_issues("TOYX", sec, model)
    assert any("DUP" in x and "duplicate" in x for x in lines)
    assert any("MISS" in x and "7SERIES" in x for x in lines)
    assert any("NUM" in x and "4" in x for x in lines)
    assert not any(" RANGE " in x or " OK " in x for x in lines)


def test_function_review_and_class_notes_reach_the_report(tmp_path):
    out = tmp_path / "catalog"
    u = tmp_path / "unisims"
    u.mkdir()
    (u / "TOYSER.v").write_text(
        "module TOYSER(input TSLIP, TCE1, TCE2, TCLK, TDIV, TSEL, TODD); endmodule\n"
    )
    (u / "IDDR.v").write_text("module IDDR(output Q1, input C, S, R); endmodule\n")
    report = build_all(FIX / "ug953_layouts.txt", ["TOYSER", "IDDR"], out, [u], family="7series")
    assert "TOYSER: port TODD UG953 function needs review" in report
    assert any(x.startswith("IDDR: port S class depends on SRTYPE") for x in report)
