# SPDX-License-Identifier: Apache-2.0
import dataclasses
import json
import shutil
from pathlib import Path

import pytest
from click.testing import CliRunner

from xut import portability
from xut.catalog.unisim import HdlModule, HdlParam, HdlPort
from xut.cli import main
from xut.modelsrc import ModelSource
from xut.portability import (
    Row,
    classify,
    configurations,
    failure,
    flipped,
    parse,
    render,
    smoke_top,
)
from xut.verilatorize.driver import ModelEntry

FIX = Path(__file__).parent / "fixtures" / "verilatorize"

TOY = HdlModule(
    "TOY",
    Path("TOY.v"),
    ports=[
        HdlPort("D", "input", 4),
        HdlPort("C", "input", 1),
        HdlPort("Q", "output", 1),
        HdlPort("IO", "inout", 2),
    ],
    params=[HdlParam("INIT", "bits", 1, "1'b0")],
)


def test_smoke_top_ties_inputs_low_and_leaves_outputs_and_inouts_as_wires():
    text = smoke_top(TOY)
    assert text.startswith(
        "// SPDX-License-Identifier: Apache-2.0\n// GENERATED by xut portability"
    )
    assert "`timescale 1ps / 1ps\nmodule xut_smoke;\n" in text
    assert "  reg  [3:0] i_D = 0;\n  reg  [0:0] i_C = 0;\n" in text
    assert "  wire [0:0] o_Q;\n  wire [1:0] io_IO;\n" in text
    assert "  TOY dut (.D(i_D), .C(i_C), .Q(o_Q), .IO(io_IO));\n" in text
    assert '  initial begin #200000; $display("XUT_SMOKE_OK"); $finish; end\nendmodule\n' in text


def test_smoke_top_passes_overrides_as_parameters():
    text = smoke_top(TOY, {"INIT": "1'b1", "A_STR": '"X"'})
    assert '  TOY #(.A_STR("X"), .INIT(1\'b1)) dut (' in text


@pytest.mark.parametrize(
    ("log", "want"),
    [
        (
            "%Error-UNSUPPORTED: /m/X.v:10:1: Unsupported: Verilog 1995 UDP Tables. "
            "Use --bbox-unsup to ignore tables.",
            "udp",
        ),
        ("%Error-UNSUPPORTED: /m/STARTUPE2.v:40:3: Unsupported: tri1 nets", "tri0-tri1"),
        ("/m/X.v:12: sorry: real variables are not supported here", "real"),
        ("/m/GTXE2_CHANNEL.v:99: error: Unknown module type: SIP_GTXE2_CHANNEL", "secureip"),
        ("%Error: /m/E.v:1:1: file is encrypted (`pragma protect)", "secureip"),
        ("%Error-UNSUPPORTED: /m/S.v:5: Unsupported: Strength specifier", "strength"),
        ("%Error-UNSUPPORTED: /m/D.v:5: Unsupported: Verilog 1995 deassign", "deassign"),
        ("xut-smoke: build exit 0\nxut-smoke: timeout (124)", "timeout"),
        (
            "xut-smoke: build exit 0\nxut-smoke: timeout (137)\n"
            "xut-container: oom-killed at memory cap 4g",
            "oom",
        ),
        ("%Error: /m/X.v:3:5: syntax error, unexpected IDENTIFIER", "other"),
        ("Error: [Unisim MMCME2_ADV-1] CLKIN1_PERIOD is not set", "other"),
    ],
)
def test_classify(log, want):
    assert classify(log) == want


def test_classify_ignores_warnings_and_non_error_lines():
    log = "%Warning-REALCVT: /m/X.v:1: real converted\nINFO: using a real clock\n%Error: boom"
    assert classify(log) == "other"
    assert failure(log, 1) == "other: %Error: boom"


def test_oom_is_a_category_and_its_reason_names_the_cap():
    assert "oom" in portability.CATEGORIES
    log = (
        "%Error: /m/X.v:1: some error\nxut-smoke: timeout (137)\n"
        "xut-container: oom-killed at memory cap 4g\n"
    )
    assert failure(log, 137) == "oom: xut-container: oom-killed at memory cap 4g"


def test_failure_without_an_error_line_names_the_exit():
    assert failure("xut-smoke: build exit 0\nxut-smoke: run exit 0\n", 0) == (
        "other: exit 0, no XUT_SMOKE_OK"
    )
    assert failure("", None) == "other: the script did not finish"


@pytest.mark.parametrize(
    ("param", "want"),
    [
        (HdlParam("IS_C_INVERTED", "bits", 1, "1'b0"), "1'b1"),
        (HdlParam("IS_C_INVERTED", "bits", 1, "1'b1"), "1'b0"),
        (HdlParam("IS_OPMODE_INVERTED", "bits", 7, "7'b0000000"), "7'b1111111"),
        (HdlParam("IS_A_INVERTED", "bits", 4, "4'h5"), "4'b1010"),
        (HdlParam("IS_X_INVERTED", "integer", None, 0), "1"),
        (HdlParam("IS_X_INVERTED", "bits", 1, "1'bx"), None),
        (HdlParam("IS_X_INVERTED", "string", None, "FALSE"), None),
    ],
)
def test_flipped(param, want):
    assert flipped(param) == want


def test_configurations_add_generate_configs_and_each_inversion(tmp_path):
    f = tmp_path / "INV.v"
    f.write_text(
        "// SPDX-License-Identifier: Apache-2.0\n"
        "module INV #(parameter [0:0] IS_C_INVERTED = 1'b0, parameter [0:0] IS_D_INVERTED "
        '= 1\'b0, parameter MODE = "A") (output Q, input C, input D);\n'
        '  generate if (MODE == "B") begin : g assign Q = D; end else begin : h assign Q = C;'
        " end endgenerate\nendmodule\n"
    )
    from xut.catalog.unisim import parse_module

    cfgs, notes = configurations(f, parse_module(f, "INV"))
    assert cfgs == [{}, {"MODE": '"B"'}, {"IS_C_INVERTED": "1'b1"}, {"IS_D_INVERTED": "1'b1"}]
    assert notes == []


ROWS = [
    Row("FDRE", "yes", "yes", "transformed", "pass", ["glbl.GSR", "CE", "R"], [], ""),
    Row(
        "XADC",
        "yes",
        "no",
        "unchanged",
        "—",
        [],
        [],
        "verilator: real: %Error: x | y \\ z [default]",
    ),
    Row("IBUFDS", "yes", "no: verilatorize: IBUFDS: a z-compare | on I_in", "unsupported", "—"),
    Row(
        "BUFGMUX",
        "yes",
        "yes",
        "unchanged (gated: BUFGCTRL)",
        "pass",
        [],
        ["CLK"],
        "note: no generate configurations",
    ),
]


def _meta():
    return {
        "generated": "2026-09-26T20:00Z",
        "head": "abc1234",
        "image": "xut-sim:1",
        "digest": "sha256:d",
    }


def test_render_layout():
    md = render({"unisim-2025.2": ROWS}, _meta())
    assert md.startswith(
        "<!-- GENERATED by xut portability — do not edit -->\n# UNISIM portability\n"
    )
    assert (
        "Generated by `xut portability` on 2026-09-26T20:00Z at abc1234. Container xut-sim:1 "
        "sha256:d." in md
    )
    assert "## unisim-2025.2\n\n| simulator | yes | no |\n|---|---|---|\n" in md
    assert "| iverilog | 4 | 0 |\n| verilator | 2 | 2 |\n" in md
    assert "| FDRE | yes | yes | transformed | pass | glbl.GSR, CE, R | — |  |\n" in md
    assert (
        "| XADC | yes | no | unchanged | — | — | — | verilator: real: %Error: x \\| y \\\\ z" in md
    )


def test_render_parse_round_trip():
    table = {"unisim-2025.2": ROWS, "unisim-gh-2020.1": ROWS[:2]}
    md = render(table, {**_meta(), "sources": {"unisim-2025.2": {
        "generated": "g", "head": "h", "models": 4, "configurations": 9, "models_glob": None,
    }}})  # fmt: skip
    got = parse(md)
    assert list(got) == ["unisim-2025.2", "unisim-gh-2020.1"]
    for ms, rows in table.items():
        assert got[ms] == {r.model: r for r in rows}


def test_parse_refuses_a_malformed_row():
    md = render({"s": ROWS[:1]}, _meta()).replace("| pass |", "|")
    with pytest.raises(portability.PortabilityError, match="8 cells"):
        parse(md)


def test_row_gated_and_why():
    assert ROWS[0].gated and ROWS[3].gated and not ROWS[1].gated and not ROWS[2].gated
    assert ROWS[1].why("verilator") == "real: %Error: x | y \\ z [default]"
    assert ROWS[2].why("verilator") == "verilatorize: IBUFDS: a z-compare | on I_in"


def _entry(**kw) -> ModelEntry:
    return ModelEntry(kw.pop("status", "transformed"), "sha", **kw)


@pytest.mark.parametrize(
    ("entry", "gate", "vz", "equiv"),
    [
        (_entry(equiv={"default": "pass", "INIT=1'b1": "pass"}), None, "transformed", "pass"),
        (_entry(), None, "transformed", "—"),
        (
            _entry(
                equiv={"default": "pass", "A=1": "fail"}, equiv_reason={"A=1": "2 mismatch(es)"}
            ),
            None,
            "transformed",
            "fail",
        ),
        (_entry(status="unchanged"), None, "unchanged", "—"),
        (
            _entry(status="unchanged", depends_on_transformed=["C"], equiv={"default": "error"}),
            None,
            "unchanged (gated: C)",
            "error",
        ),
        (
            _entry(status="unsupported", reason="X: nested generate\nmore"),
            "no: verilatorize: X: nested generate",
            "unsupported",
            "—",
        ),
        (
            _entry(status="unchanged", depends_on_unsupported=["IBUFDS"]),
            "no: blocked by refused dependency IBUFDS",
            "unchanged",
            "—",
        ),
        (
            _entry(depends_on_unsupported=["MMCME3_ADV"]),
            "no: blocked by refused dependency MMCME3_ADV",
            "transformed",
            "blocked",
        ),
    ],
)
def test_manifest_cells(entry, gate, vz, equiv):
    assert portability._gate(entry) == gate
    assert portability._vz_cell(entry) == vz
    assert portability._equiv(entry, {})[0] == equiv


def test_equiv_reason_names_the_first_failing_configuration():
    e = _entry(equiv={"default": "pass", "A=1": "fail"}, equiv_reason={"A=1": "2 mismatch(es)"})
    assert portability._equiv(e, {})[1] == "equiv: fail [A=1] (1 of 2): 2 mismatch(es)"


def test_equiv_needs_every_generate_configuration():
    """PR #10 nit: a pass needs a verdict for the default and every generate
    configuration, not only for those recorded (a --no-check manifest)."""
    e = _entry(equiv={"default": "pass"})
    assert portability._equiv(e, {}, ["default", "A=1"]) == (
        "—",
        "equiv: no verdict for [A=1]",
    )
    assert portability._equiv(e, {}, ["default"]) == ("pass", "")


@pytest.mark.parametrize(
    ("child", "cell"), [({"AREG=0": "error"}, "error"), ({"AREG=0": "fail"}, "fail"),
                        ({}, "—"), ({"AREG=0": "pass"}, "pass")],
)  # fmt: skip
def test_equiv_folds_in_the_transformed_descendants(child, cell):
    """Ruling S50: a parent's cell is a pass only when each transformed descendant passes
    for the parameterisation the parent instantiates it with."""
    dep = [{"model": "C", "attrs": {"AREG": "0"}, "key": "AREG=0"}]
    parent = _entry(
        status="unchanged",
        depends_on_transformed=["C"],
        equiv={"default": "pass"},
        dep_configs={"default": dep},
    )
    models = {"C": _entry(equiv={"default": "pass", **child})}
    got, why = portability._equiv(parent, models)
    assert got == cell, why
    if cell != "pass":
        assert why.startswith("equiv: ") and "transformed descendant C [AREG=0]" in why
    # never derived: no verdict, fail closed
    parent.dep_configs.clear()
    assert portability._equiv(parent, models)[0] == "—"


def _write_result(root: Path, ms: str, rows: list[Row], glob: str | None = None) -> None:
    doc = {
        "model_source": ms, **_meta(), "models_glob": glob, "models": len(rows),
        "configurations": 2 * len(rows), "rows": [dataclasses.asdict(r) for r in rows],
    }  # fmt: skip
    d = root / "build" / "portability" / ("partial" if glob else "")
    d.mkdir(parents=True, exist_ok=True)
    (d / f"{ms}.json").write_text(json.dumps(doc))


def test_load_results_reads_full_runs_only(tmp_path):
    _write_result(tmp_path, "unisim-2025.2", ROWS)
    _write_result(tmp_path, "unisim-gh-2020.1", ROWS[:1], glob="FD*")  # partial/: ignored
    rows, meta = portability.load_results(tmp_path)
    assert list(rows) == ["unisim-2025.2"] and rows["unisim-2025.2"] == ROWS
    assert meta["head"] == "abc1234" and meta["sources"]["unisim-2025.2"]["configurations"] == 8


def test_status_generate_also_writes_portability_when_results_exist(tmp_path, monkeypatch):
    (tmp_path / "status" / "7series").mkdir(parents=True)
    (tmp_path / "log").mkdir()
    monkeypatch.setattr("xut.paths.repo_root", lambda start=None: tmp_path)
    monkeypatch.setattr("xut.status.current_branch", lambda: "main")
    monkeypatch.setattr("xut.workunits.load_units", lambda root: {})
    monkeypatch.setattr("xut.workunits.load_family", lambda root: "7series")
    r = CliRunner().invoke(main, ["status", "generate"])
    assert r.exit_code == 0, r.output
    assert not (tmp_path / "status" / "PORTABILITY.md").exists()
    _write_result(tmp_path, "unisim-2025.2", ROWS)
    r = CliRunner().invoke(main, ["status", "generate"])
    assert r.exit_code == 0 and "PORTABILITY.md" in r.output, r.output
    got = parse((tmp_path / "status" / "PORTABILITY.md").read_text())
    assert got == {"unisim-2025.2": {r.model: r for r in ROWS}}


def test_portability_write_refuses_off_main(monkeypatch):
    monkeypatch.setattr("xut.status.current_branch", lambda: "infra/verilatorize")
    r = CliRunner().invoke(main, ["portability", "--write"])
    assert r.exit_code != 0 and "only main regenerates it" in r.output
    r = CliRunner().invoke(main, ["portability", "--write", "--force", "--models", "FD*"])
    assert r.exit_code != 0 and "--write needs a full run" in r.output


# --- the container run on the Task 12 fixture model source ------------------------------------

SIPUSER = """\
// SPDX-License-Identifier: Apache-2.0
module SIPUSER (output O, input I);
  SIP_NOSUCH u (.O(O), .I(I));
endmodule
"""
STOPPER = """\
// SPDX-License-Identifier: Apache-2.0
`timescale 1ps / 1ps
module STOPPER #(parameter [0:0] IS_C_INVERTED = 1'b0) (output O, input C);
  assign O = C ^ IS_C_INVERTED;
  initial if (IS_C_INVERTED) begin
    #1000 $display("Error: [Unisim STOPPER-1] IS_C_INVERTED=1 is not supported");
    $finish;
  end
endmodule
"""
BLOCKED = """\
// SPDX-License-Identifier: Apache-2.0
module BLOCKED (output [1:0] Q, input C, input [1:0] D, input S);
  VZBADSEL u (.Q(Q), .C(C), .D(D), .S(S));
endmodule
"""


@pytest.fixture
def fixture_source(tmp_path):
    src = tmp_path / "src"
    uni = src / "unisims"
    uni.mkdir(parents=True)
    shutil.copy(FIX / "glbl.v", src / "glbl.v")
    for f, model in (
        ("vz_trig.v", "VZTRIG"),
        ("vz_parent.v", "VZPARENT"),
        ("vz_child.v", "VZCHILD"),
        ("vz_bad_select.v", "VZBADSEL"),
    ):
        shutil.copy(FIX / f, uni / f"{model}.v")
    for model, text in (("SIPUSER", SIPUSER), ("STOPPER", STOPPER), ("BLOCKED", BLOCKED)):
        (uni / f"{model}.v").write_text(text)
    (uni / "PLAIN.v").write_text(
        "// SPDX-License-Identifier: Apache-2.0\nmodule PLAIN (output O, input I);\n"
        "  assign O = I;\nendmodule\n"
    )
    return ModelSource("test-src", src)


@pytest.mark.container
def test_run_smoke_on_the_fixture_model_source(tmp_path, fixture_source):
    root = tmp_path / "root"
    root.mkdir()
    lines: list[str] = []
    rows = portability.run_smoke(fixture_source, jobs=8, root=root, progress=lines.append)
    got = {r.model: r for r in rows}
    assert sorted(got) == sorted(p.stem for p in fixture_source.unisims.glob("*.v"))
    assert (got["VZTRIG"].iverilog, got["VZTRIG"].verilator) == ("yes", "yes")
    assert (got["VZTRIG"].verilatorize, got["VZTRIG"].equiv) == ("transformed", "pass")
    assert got["VZTRIG"].triggers == ["CLR", "PRE", "glbl.GSR"]
    assert got["PLAIN"] == Row("PLAIN", "yes", "yes", "unchanged", "—")
    assert got["VZPARENT"].verilatorize == "unchanged (gated: VZCHILD)"
    assert (got["VZPARENT"].equiv, got["VZPARENT"].verilator) == ("pass", "yes")
    assert got["VZBADSEL"].verilator.startswith("no: verilatorize: ")
    # a procedural assign to a bit select: pyslang cannot read its ports, so no smoke top
    assert got["VZBADSEL"].iverilog == "no"
    assert got["VZBADSEL"].reason.startswith("iverilog: other: smoke: cannot read its ports: 1 ")
    assert got["BLOCKED"].verilator == "no: blocked by refused dependency VZBADSEL"
    sip = got["SIPUSER"]
    assert (sip.iverilog, sip.verilator) == ("no", "no")
    assert "iverilog: secureip: " in sip.reason and "verilator: secureip: " in sip.reason
    stop = got["STOPPER"]
    assert (stop.iverilog, stop.verilator) == ("no", "no"), stop
    assert "iverilog: other: Error: [Unisim STOPPER-1]" in stop.reason
    assert stop.reason.split("; ")[0].endswith("[IS_C_INVERTED=1'b1]"), stop.reason
    # the result file and the progress lines
    doc = json.loads((root / "build/portability/test-src.json").read_text())
    assert [r["model"] for r in doc["rows"]] == sorted(got)
    assert doc["configurations"] == 8  # STOPPER has 2 (IS_C_INVERTED flipped), VZBADSEL 0
    smoke = [ln for ln in lines if ln.startswith("progress: done=")]
    total = int(smoke[0].split("total=")[1].split()[0])
    assert smoke[-1].startswith(f"progress: done={total} total={total} ")
    assert not any(ln.startswith("progress: done=") for ln in lines[: lines.index(smoke[0])])
    work = root / "build/portability/test-src"
    assert (work / "VZTRIG/default/smoke.v").is_file()
    assert (work / "VZTRIG/default/verilator.rc").read_text().strip() == "0"
    assert not (work / "VZTRIG/default/obj").exists()  # removed after the run
    assert not (work / "VZBADSEL/default/verilator.sh").exists()  # refused: never built
    assert not (work / "driver.sh").exists()  # one container per script (Ruling S48)
    assert (work / "jobs.txt").read_text().count("\n") == total
    assert parse(render({"test-src": rows}, _meta()))["test-src"] == got


# --- Ruling S48: one container per smoke script -----------------------------------------------

OOM_LINE = "xut-container: oom-killed at memory cap 4g"


class _PoolEx:
    """A fake executor: runs each smoke script by hand. ``behaviour[script]`` is ``ok`` (the
    script writes rc 0 and SMOKE_OK), ``oom-early`` (killed before it writes its rc),
    ``oom-child`` (a child killed: the script still writes rc 137) or ``timeout``."""

    image = "fake:1"

    def __init__(self, behaviour, delay=0.05):
        import threading

        self.behaviour, self.delay = behaviour, delay
        self.lock = threading.Lock()
        self.active = self.peak = 0
        self.started: list[str] = []
        self.calls: list[tuple] = []

    def guest(self, path):
        return str(path)

    def run(self, argv, cwd, log, timeout_s, env=None):
        import time

        from xut.container import RunTimeout

        script = argv[1]
        with self.lock:
            self.calls.append((argv, cwd, log))
            self.started.append(script)
            self.active += 1
            self.peak = max(self.peak, self.active)
        try:
            time.sleep(self.delay)
            d, tool = cwd / Path(script).parent, Path(script).stem
            how = self.behaviour[script]
            with log.open("a") as f:
                f.write(f"$ {' '.join(argv)}   [container fake]\n")
            if how == "timeout":
                raise RunTimeout("timeout after 1s: bash")
            if how == "docker-fail":  # docker run itself failed: the script never ran
                with log.open("a") as f:
                    f.write("docker: Error response from daemon: boom\n")
                return 125
            if how == "oom-no-done":  # killed between writing its rc and done.txt
                (d / f"{tool}.log").write_text("xut-smoke: timeout (137)\n")
                (d / f"{tool}.rc").write_text("137\n")
                with log.open("a") as f:
                    f.write(OOM_LINE + "\n")
                return 137
            if how == "oom-early":
                (d / f"{tool}.log").write_text("xut-smoke: build exit 0\n")
                with log.open("a") as f:
                    f.write(OOM_LINE + "\n")
                return 137
            if how == "oom-child":
                (d / f"{tool}.log").write_text("xut-smoke: timeout (137)\n")
                (d / f"{tool}.rc").write_text("137\n")
            else:
                (d / f"{tool}.log").write_text(f"{portability.SMOKE_OK}\n")
                (d / f"{tool}.rc").write_text("0\n")
            with (cwd / "done.txt").open("a") as f:
                f.write(f"{Path(script).with_suffix('')}\n")
            if how == "oom-child":
                with log.open("a") as f:
                    f.write(OOM_LINE + "\n")
            return 0
        finally:
            with self.lock:
                self.active -= 1


def _pool_work(tmp_path, n):
    work = tmp_path / "w"
    scripts = []
    for i in range(n):
        d = work / f"M{i}" / "default"
        d.mkdir(parents=True)
        for tool in portability.TOOLS:
            scripts.append(f"M{i}/default/{tool}.sh")
    (work / "done.txt").write_text("")
    return work, scripts


def test_run_scripts_one_container_per_script_at_most_jobs_at_once(tmp_path):
    work, scripts = _pool_work(tmp_path, 6)
    ex = _PoolEx(dict.fromkeys(scripts, "ok"))
    lines: list[str] = []
    portability._run_scripts(ex, work, scripts, jobs=3, progress=lines.append)
    assert sorted(ex.started) == sorted(scripts)
    assert 1 < ex.peak <= 3
    for argv, cwd, log in ex.calls:
        assert argv == ["bash", argv[1]] and cwd == work
        assert log == work / Path(argv[1]).with_suffix(".container.log")
    assert len((work / "done.txt").read_text().splitlines()) == len(scripts)
    assert lines[-1].startswith(f"progress: done={len(scripts)} total={len(scripts)} ")


def test_run_scripts_start_in_jobs_txt_order(tmp_path):
    work, scripts = _pool_work(tmp_path, 3)
    order = list(reversed(scripts))
    ex = _PoolEx(dict.fromkeys(scripts, "ok"), delay=0)
    portability._run_scripts(ex, work, order, jobs=1, progress=lambda _: None)
    assert ex.started == order


def test_run_scripts_record_an_oom_kill(tmp_path):
    work, scripts = _pool_work(tmp_path, 2)
    early, child = scripts[0], scripts[2]
    beh = dict.fromkeys(scripts, "ok") | {early: "oom-early", child: "oom-child"}
    ex = _PoolEx(beh, delay=0)
    portability._run_scripts(ex, work, scripts, jobs=2, progress=lambda _: None)
    for s in (early, child):
        d, tool = work / Path(s).parent, Path(s).stem
        assert (d / f"{tool}.rc").read_text().strip() == "137"
        log = (d / f"{tool}.log").read_text()
        assert log.count(OOM_LINE) == 1
        ok, why = portability._outcome(d, tool)
        assert not ok and why == f"oom: {OOM_LINE}"
    done = (work / "done.txt").read_text().splitlines()
    assert sorted(done) == sorted(str(Path(s).with_suffix("")) for s in scripts)


def test_run_scripts_record_a_host_timeout(tmp_path):
    work, scripts = _pool_work(tmp_path, 1)
    ex = _PoolEx(dict.fromkeys(scripts, "ok") | {scripts[1]: "timeout"}, delay=0)
    portability._run_scripts(ex, work, scripts, jobs=2, progress=lambda _: None)
    d, tool = work / Path(scripts[1]).parent, Path(scripts[1]).stem
    ok, why = portability._outcome(d, tool)
    assert not ok and why.startswith("timeout: ")
    assert len((work / "done.txt").read_text().splitlines()) == 2


# --- Ruling S48/S48a: --jobs is capped by the memory budget --------------------------------

JOBS_COMMANDS = ["portability", "run", "verilatorize"]


def _stub_runs(monkeypatch):
    """Every real run raises: a missing refusal must never start one from a unit test."""
    import xut.verilatorize.driver as vz
    from xut import run as run_mod

    def never(*a, **kw):
        raise AssertionError("a refused --jobs reached the run")

    monkeypatch.setattr(portability, "run_smoke", never)
    monkeypatch.setattr(run_mod, "run_tests", never)
    monkeypatch.setattr(vz, "verilatorize", never)


def _jobs_options():
    """(command path, option) for every --jobs / -j option of the CLI."""
    import click

    out = []

    def walk(cmd, path):
        for p in cmd.params:
            if isinstance(p, click.Option) and ({"--jobs", "-j"} & set(p.opts + p.secondary_opts)):
                out.append((path, p))
        for name, sub in getattr(cmd, "commands", {}).items():
            walk(sub, [*path, name])

    walk(main, [])
    return out


def test_every_jobs_option_is_capped():
    from xut.cli import _jobs_cap

    found = _jobs_options()
    assert sorted(" ".join(p) for p, _ in found) == sorted(JOBS_COMMANDS)
    assert all(opt.callback is _jobs_cap for _, opt in found)


@pytest.mark.parametrize("cmd", JOBS_COMMANDS)
def test_cli_refuses_jobs_over_the_budget(cmd, monkeypatch):
    _stub_runs(monkeypatch)
    monkeypatch.delenv("XUT_CONTAINER_MEMORY", raising=False)
    monkeypatch.delenv("XUT_MEMORY_BUDGET", raising=False)
    r = CliRunner().invoke(main, [cmd, "--jobs", "26"])
    assert r.exit_code == 2, r.output
    for want in ("--jobs 26", "100g", "4g", "25"):
        assert want in r.output, r.output


@pytest.mark.parametrize("cmd", JOBS_COMMANDS)
def test_cli_jobs_limit_follows_the_container_cap(cmd, monkeypatch):
    _stub_runs(monkeypatch)
    monkeypatch.setenv("XUT_CONTAINER_MEMORY", "16g")
    monkeypatch.delenv("XUT_MEMORY_BUDGET", raising=False)
    r = CliRunner().invoke(main, [cmd, "--jobs", "7"])
    assert r.exit_code == 2 and "--jobs 7" in r.output and "16g" in r.output, r.output
    assert "at most 6" in r.output, r.output


def test_cli_jobs_defaults_stay_within_the_limit(monkeypatch):
    """The defaults are 1, below min(cpu_count, 24, max_jobs()); this guards that upper
    bound (with the default budget and cap, max_jobs() is 25) should a default grow."""
    import os

    from xut.container import max_jobs

    monkeypatch.delenv("XUT_CONTAINER_MEMORY", raising=False)
    monkeypatch.delenv("XUT_MEMORY_BUDGET", raising=False)
    limit = min(os.cpu_count() or 1, 24, max_jobs()[0])
    for path, opt in _jobs_options():
        assert 1 <= opt.default <= limit, (path, opt.default)


def test_run_scripts_interrupt_kills_the_live_containers(tmp_path, monkeypatch):
    from xut import container

    work, scripts = _pool_work(tmp_path, 1)  # two scripts: jobs=1 leaves no race
    killed: list[bool] = []
    monkeypatch.setattr(container, "kill_live", lambda: killed.append(True) or [])

    class Interrupting(_PoolEx):
        def run(self, argv, cwd, log, timeout_s, env=None):
            if argv[1] == scripts[1]:
                raise KeyboardInterrupt
            return super().run(argv, cwd, log, timeout_s, env)

    ex = Interrupting(dict.fromkeys(scripts, "ok"), delay=0)
    with pytest.raises(KeyboardInterrupt):
        portability._run_scripts(ex, work, scripts, jobs=1, progress=lambda _: None)
    assert killed == [True]
    assert ex.started == [scripts[0]]  # the queued scripts were cancelled


def test_a_partial_run_never_touches_the_full_run_directory(tmp_path, fixture_source, monkeypatch):
    """S48a M-4: a --models run works under build/portability/partial/<ms>/."""
    import types

    import xut.verilatorize.driver as vz
    from xut import container

    root = tmp_path / "root"
    full = root / "build/portability/test-src"
    full.mkdir(parents=True)
    (full / "keep.txt").write_text("a full run's logs\n")
    monkeypatch.setattr(vz, "verilatorize", lambda *a, **kw: types.SimpleNamespace(models={}))
    monkeypatch.setattr(container, "sim_tool_versions", lambda ex, work: {"iverilog": "x"})
    monkeypatch.setattr(container, "image_digest", lambda image=None: "sha256:x")
    ran: list[Path] = []
    monkeypatch.setattr(portability, "_run_scripts", lambda exe, work, *a: ran.append(work))
    portability.run_smoke(fixture_source, jobs=1, models="PLAIN", root=root, progress=print)
    assert (full / "keep.txt").read_text() == "a full run's logs\n"
    assert ran == [root / "build/portability/partial/test-src"]
    assert (ran[0] / "PLAIN/default/smoke.v").is_file()
    assert (root / "build/portability/partial/test-src.json").is_file()
    assert portability.out_dir(fixture_source, root) == full


def test_run_scripts_record_the_container_exit_when_no_rc(tmp_path):
    """S48a M-5: docker run's own failure is in the cell's reason."""
    work, scripts = _pool_work(tmp_path, 1)
    ex = _PoolEx(dict.fromkeys(scripts, "ok") | {scripts[0]: "docker-fail"}, delay=0)
    portability._run_scripts(ex, work, scripts, jobs=2, progress=lambda _: None)
    d, tool = work / Path(scripts[0]).parent, Path(scripts[0]).stem
    want = "xut-container: exit 125: docker: Error response from daemon: boom"
    assert want in (d / f"{tool}.log").read_text()
    ok, why = portability._outcome(d, tool)
    assert not ok and why == f"other: {want}"
    assert not (d / f"{tool}.rc").exists()
    assert len((work / "done.txt").read_text().splitlines()) == 2


def test_run_scripts_count_every_script_done_exactly_once(tmp_path):
    """S48a M-7: a script killed after its rc but before done.txt is still counted once."""
    work, scripts = _pool_work(tmp_path, 2)
    beh = dict.fromkeys(scripts, "ok") | {scripts[0]: "oom-no-done", scripts[1]: "oom-early"}
    lines: list[str] = []
    portability._run_scripts(_PoolEx(beh, delay=0), work, scripts, jobs=2, progress=lines.append)
    done = (work / "done.txt").read_text().splitlines()
    assert sorted(done) == sorted(str(Path(s).with_suffix("")) for s in scripts)
    assert lines[-1].startswith(f"progress: done={len(scripts)} total={len(scripts)} ")
