# SPDX-License-Identifier: Apache-2.0
"""Tests for `xut status generate` (PROGRESS/TODO/LOG rendering, spec §11)."""

from click.testing import CliRunner
from xut.cli import main
from xut.status import render_log, render_progress, render_todo
from xut.workunits import WorkUnit


def _unit(name="flops", group="register", primitives=("FDRE", "FDSE")):
    return {name: WorkUnit(name=name, family="7series", primitives=primitives, group_dirs=(group,))}


def _status(
    primitive, work_unit="flops", results=None, covered=None, uncovered=None, findings=None
):
    return {
        "primitive": primitive,
        "family": "7series",
        "work_unit": work_unit,
        "model_library": "unisims",
        "measured": {"tree_hash": None, "tools": {}},
        "results": results or {},
        "findings": findings or [],
        "coverage": {"covered": covered or [], "uncovered": uncovered or []},
        "notes": "",
    }


def test_render_progress_marks_pass_and_fail_and_not_run():
    fdre = _status(
        "FDRE",
        results={"L1/iverilog/rtl": "pass", "L1/hw/vivado": "fail"},
    )
    fdse = _status("FDSE")
    out = render_progress([fdre, fdse], _unit())

    lines = out.splitlines()
    fdre_row = next(line for line in lines if line.startswith("| FDRE "))
    fdse_row = next(line for line in lines if line.startswith("| FDSE "))

    # FDRE's L1 cell (python xsim iverilog verilator hw) has a pass and a fail mark.
    # Columns: '' Primitive Unit Model L0 L1 L2 L3 Coverage Uncovered Findings ''
    l1_cell = fdre_row.split("|")[5]
    assert "✓" in l1_cell
    assert "✗" in l1_cell

    # FDSE has no results at all: every level cell is all not-run marks.
    for cell in fdse_row.split("|")[4:8]:
        assert cell.strip() == "–" * 5


def test_render_progress_coverage_percentage():
    fdre = _status("FDRE", covered=["port:C", "port:D"], uncovered=[f"port:{i}" for i in range(6)])
    out = render_progress([fdre], _unit(primitives=("FDRE",)))
    assert "25%" in out


def test_render_log_orders_by_filename(tmp_path):
    (tmp_path / "2026-01-01T0000-a-first.md").write_text("# First Entry\n\nbody\n")
    (tmp_path / "2026-02-02T0000-b-second.md").write_text("# Second Entry\n\nbody\n")
    out = render_log(tmp_path)
    assert out.index("First Entry") < out.index("Second Entry")


def test_render_todo_lists_uncovered_bins_unsupported_and_findings():
    fdre = _status(
        "FDRE",
        results={"L1/hw/vivado": "unsupported"},
        uncovered=["port:R"],
        findings=["FDRE-reset-glitch"],
    )
    out = render_todo([fdre], _unit(primitives=("FDRE",)))
    assert "port:R" in out
    assert "L1/hw/vivado" in out
    assert "FDRE-reset-glitch" in out


def test_generate_refuses_off_main_without_force(monkeypatch):
    monkeypatch.setattr("xut.status.current_branch", lambda: "unit/7series/flops")
    result = CliRunner().invoke(main, ["status", "generate"])
    assert result.exit_code != 0
    assert "main" in result.output


def test_generate_allows_main(monkeypatch, tmp_path):
    monkeypatch.setattr("xut.status.current_branch", lambda: "main")
    monkeypatch.setattr("xut.paths.repo_root", lambda start=None: tmp_path)

    (tmp_path / "docs").mkdir()
    (tmp_path / "docs/work-units.yaml").write_text(
        "family: 7series\nunits:\n  flops: {group: register, primitives: [FDRE]}\n"
    )
    status_dir = tmp_path / "status/7series"
    status_dir.mkdir(parents=True)
    (status_dir / "FDRE.yaml").write_text(
        "# SPDX-License-Identifier: Apache-2.0\n"
        "primitive: FDRE\nfamily: 7series\nwork_unit: flops\nmodel_library: unisims\n"
        "measured: {tree_hash: null, tools: {}}\nresults: {}\nfindings: []\n"
        "coverage: {covered: [], uncovered: []}\nnotes: ''\n"
    )
    (tmp_path / "log").mkdir()
    (tmp_path / "log/2026-01-01T0000-main-x.md").write_text("# X\n")

    result = CliRunner().invoke(main, ["status", "generate"])
    assert result.exit_code == 0, result.output

    progress = (tmp_path / "status/PROGRESS.md").read_text()
    todo = (tmp_path / "status/TODO.md").read_text()
    log = (tmp_path / "status/LOG.md").read_text()
    for text in (progress, todo, log):
        assert text.startswith("<!-- GENERATED by xut status generate — do not edit -->")
    assert "FDRE" in progress
    assert "X" in log
