# SPDX-License-Identifier: Apache-2.0
"""Shadow-register transform (spec §6.2 steps 1-3, rev 3.3), applied as AST-anchored text
edits to the spans an :class:`~xut.verilatorize.analyze.Analysis` records.

For each procedurally-forced reg ``X`` of the model (and of every same-file helper module it
instantiates):

* the declaration of ``X`` becomes ``X__base`` (a non-ANSI ``output reg X;`` instead loses its
  ``reg`` keyword and ``X__base`` is declared next to it), and every ordinary procedural write
  to ``X`` writes ``X__base``;
* ``reg [w-1:0] X__ovr_sel = 0;`` selects the active override, and each override expression
  ``e_k`` drives its own net ``X__ovr_k`` declared with ``X``'s packed range and signedness
  (``real``/``realtime``: a variable of that type, which Icarus 12 and Verilator 5.048 both
  accept as a continuous-assignment target; a net cannot be ``real``);
* ``assign X = e_k;`` becomes ``X__ovr_sel = k;``;
* ``deassign X;`` becomes ``begin if (X__ovr_sel != 0) begin X__base = X__active();
  X__ovr_sel = 0; end end``. ``X__active()`` is a module-scope function returning the value of
  the active override expression with ``X``'s type (ruling S18: never the net ``X``, which may
  not have propagated yet). The outer ``begin ... end`` keeps an ``else`` that followed the
  ``deassign`` bound to its own ``if``;
* a read of ``X`` right after its ``assign``/``deassign`` in the same block (``stale_reads``)
  reads ``X__base`` after a ``deassign``, and after ``assign X = e_k;`` reads ``X__now``, a
  variable of ``X``'s type that the rewritten ``assign`` sets to ``e_k`` (the value of the
  active override, typed exactly as the forced value);
* a read of ``X`` right after an ordinary blocking write of ``X`` in the same block (on some
  path, no delay between; ``StaleRead`` ``FRESH``) would see the net ``X`` before it follows
  ``X__base``. It reads ``X__rd`` instead, set right before the innermost statement holding
  the read to ``(X__ovr_sel == 0) ? X__base : X__active()``: ``X``'s current value in every
  override state (a read in a loop header, or in a block with implicit sensitivity, is
  refused);
* ``X`` itself becomes ``assign X = (X__ovr_sel == 0) ? X__base : (X__ovr_sel == 1) ? X__ovr_1
  : ...;`` at the end of the module.

The ``deassign`` capture is a blocking write to ``X__base`` in level-sensitive logic, while the
model's own writes to it are usually non-blocking. Verilator refuses that mix by default
(``BLKANDNBLK``: it cannot prove the bits independent); with the check waived for ``X__base``
it uses its masked-shadow scheme, which commits the non-blocking updates over the blocking
value in the NBA region. That keeps the Verilog order only while the forcing block runs in the
active region, before the commit (a release driven by a primitive input or glbl, coincident
with a clock edge, still loses to the edge's write). It is NOT order-safe when the forcing
block is itself triggered from the NBA region: the reviewer's VZCE (release driven by
``always @(posedge C) r <= R;``) diverges on Verilator 5.048. So a forced reg with a
``deassign`` whose trigger cone contains a reg written by a non-blocking assignment
(``ForcedReg.nba_cone``) is refused (ruling S28). The waiver is a ``lint_off``/``lint_on``
metacomment pair around the ``X__base`` name, so it covers that variable only. A blocking
capture is required: a non-blocking one would overwrite a non-blocking write scheduled earlier
in the same time step.

A ``deassign`` of a reg that is never procedurally assigned is a no-op: it becomes ``;``.
Anything else the rewrite cannot prove it handles raises ``TransformError`` (spec §6.2 rule 4).
"""

from __future__ import annotations

import re
import tempfile
from pathlib import Path

import pyslang

from xut.verilatorize.analyze import (
    _SYNTAX_FORCE,
    FRESH,
    Analysis,
    ForcedReg,
    Span,
    TransformError,
    _compile,
    _Source,
    _walk_syntax,
)

SPDX = "// SPDX-License-Identifier: Apache-2.0\n"
BANNER = "// GENERATED by xut verilatorize from {src} (spec §6.2). Never commit.\n"
TAIL_COMMENT = "  // xut verilatorize: shadow-register override muxes (spec §6.2)\n"

_SX = pyslang.syntax.SyntaxKind
_BLOCKS = {
    _SX.AlwaysBlock,
    _SX.AlwaysCombBlock,
    _SX.AlwaysFFBlock,
    _SX.AlwaysLatchBlock,
    _SX.InitialBlock,
    _SX.FinalBlock,
}
_IMPLICIT_BLOCKS = {_SX.AlwaysCombBlock, _SX.AlwaysLatchBlock}
_SCOPES = {
    _SX.GenerateBlock,
    _SX.LoopGenerate,
    _SX.SequentialBlockStatement,
    _SX.ParallelBlockStatement,
    _SX.TaskDeclaration,
    _SX.FunctionDeclaration,
}
_LOOPS = {
    _SX.LoopStatement,
    _SX.ForLoopStatement,
    _SX.DoWhileStatement,
    _SX.ForeverStatement,
    _SX.ForeachLoopStatement,
}
_REAL = ("real", "realtime")
#: Waives Verilator's BLKANDNBLK check for the one variable it wraps (module docstring).
_WAIVE = "/* verilator lint_off BLKANDNBLK */ {} /* verilator lint_on BLKANDNBLK */"


def _apply(model: str, text: str, edits: list[tuple[int, int, str]]) -> str:
    edits = sorted(edits, key=lambda e: (e[0], e[1]))  # stable: same-offset inserts keep order
    for (_s1, e1, _), (s2, _e2, _) in zip(edits, edits[1:], strict=False):
        if s2 < e1:
            raise TransformError(model, f"overlapping rewrite edits at offset {s2}")
    out, pos = [], 0
    for s, e, rep in edits:
        out += [text[pos:s], rep]
        pos = e
    out.append(text[pos:])
    return "".join(out)


class _Syntax:
    """The model file's syntax tree, indexed by ``str`` offset, for the checks the elaborated
    analysis cannot make (enclosing block kind, scope of override-expression names)."""

    def __init__(self, path: Path) -> None:
        self.src = _Source(path)
        tree = pyslang.syntax.SyntaxTree.fromFile(str(path))
        self._tree = tree  # keep the tree alive while its nodes are used
        self.blocks: list[tuple[int, int, bool, int]] = []  # (start, end, implicit, line)
        self.by_start: dict[int, pyslang.syntax.SyntaxNode] = {}
        self.stmts: list[tuple[int, int, pyslang.syntax.SyntaxKind]] = []
        for n in _walk_syntax(tree.root):
            if isinstance(n, pyslang.syntax.StatementSyntax):
                r = n.sourceRange
                self.stmts.append(
                    (self.src.char(r.start.offset), self.src.char(r.end.offset), n.kind)
                )
            if n.kind in _BLOCKS:
                implicit = n.kind in _IMPLICIT_BLOCKS or any(
                    c.kind == _SX.ImplicitEventControl for c in _walk_syntax(n)
                )
                r = n.sourceRange
                self.blocks.append(
                    (
                        self.src.char(r.start.offset),
                        self.src.char(r.end.offset),
                        implicit,
                        self.src.line(r.start.offset),
                    )
                )
            elif n.kind == _SX.ProceduralAssignStatement:
                self.by_start[self.src.char(n.sourceRange.start.offset)] = n

    def implicit_block_line(self, pos: int) -> int | None:
        """The line of the innermost procedural block around ``pos`` if it has implicit
        sensitivity (``@*``, ``always_comb``, ``always_latch``), else None."""
        inner = None
        for s, e, implicit, line in self.blocks:
            if s <= pos < e and (inner is None or s >= inner[0]):
                inner = (s, implicit, line)
        return inner[2] if inner is not None and inner[1] else None

    def statement(self, pos: int) -> tuple[int, int, pyslang.syntax.SyntaxKind] | None:
        """The innermost statement around ``pos``: (start, end, kind)."""
        inner = None
        for st in self.stmts:
            if st[0] <= pos < st[1] and (inner is None or (st[0], -st[1]) > (inner[0], -inner[1])):
                inner = st
        return inner

    def scoped_names(self, stmt_start: int) -> tuple[set[str], set[str]]:
        """(identifiers the override expression of the ``assign`` at ``stmt_start`` reads,
        names declared in the scopes enclosing it below module level)."""
        node = self.by_start.get(stmt_start)
        if node is None:
            raise AssertionError(f"no procedural assign syntax at offset {stmt_start}")
        reads = {
            n.identifier.valueText
            for n in _walk_syntax(node.expr.right)
            if n.kind == _SX.IdentifierName
        }
        local: set[str] = set()
        a = node.parent
        while a is not None and a.kind != _SX.ModuleDeclaration:
            if a.kind in _SCOPES:
                local |= _declared(a)
            a = a.parent
        return reads, local


def _declared(scope: pyslang.syntax.SyntaxNode) -> set[str]:
    out: set[str] = set()
    for n in _walk_syntax(scope):
        if n.kind == _SX.Declarator:
            out.add(n.name.valueText)
        elif n.kind == _SX.LoopGenerate:
            out.add(n.identifier.valueText)
        elif n.kind == _SX.GenvarDeclaration:
            out |= {i.identifier.valueText for i in n.identifiers if i.kind == _SX.IdentifierName}
    return out


def _var(x: ForcedReg, name: str) -> str:
    """A variable declaration of ``X``'s type."""
    return f"{x.type} {name};" if x.type in _REAL else f"reg {x.dims}{name};"


def _net(x: ForcedReg, name: str) -> str:
    """A continuous-assignment target of ``X``'s type (a ``real`` cannot be a net)."""
    return f"{x.type} {name};" if x.type in _REAL else f"wire {x.dims}{name};"


def _function(x: ForcedReg, exprs: list[str], w: int) -> str:
    ret = x.type if x.type in _REAL else x.dims.strip()
    name, sel = f"{x.name}__active", f"{x.name}__ovr_sel"
    head = f"  function {ret + ' ' if ret else ''}{name}();\n"
    if len(exprs) == 1:
        body = f"    {name} = {exprs[0]};\n"
    else:
        arms = [f"if ({sel} == {w}'d{k}) {name} = {e};" for k, e in enumerate(exprs[:-1], 1)]
        body = "    " + "\n    else ".join(arms) + f"\n    else {name} = {exprs[-1]};\n"
    return head + body + "  endfunction"


def _module_edits(an: Analysis, syn: _Syntax, names: set[str]) -> list[tuple[int, int, str]]:
    edits: list[tuple[int, int, str]] = [(d.start, d.end, ";") for d in an.noop_deassigns]
    tail: list[str] = []
    fresh: dict[tuple[int, int], list[str]] = {}  # statement -> refreshes to run before it
    for x in an.forced.values():
        edits += _reg_edits(an, x, syn, names, tail, fresh)
    # A read of X right after an ordinary blocking write (StaleRead FRESH) reads X__rd, set
    # just before the innermost statement holding the read to X's current value. The
    # statement becomes `begin <refreshes> <statement> end`: still one statement, so an
    # `else` after it keeps its `if`. Inner statements close first (same end offset).
    for (start, end), refs in sorted(fresh.items(), key=lambda kv: -kv[0][0]):
        edits.append((start, start, "begin " + " ".join(dict.fromkeys(refs)) + " "))
        edits.append((end, end, " end"))
    if tail:
        edits.append((an.endmodule, an.endmodule, TAIL_COMMENT + "\n".join(tail) + "\n"))
    return edits


def _reg_edits(
    an: Analysis,
    x: ForcedReg,
    syn: _Syntax,
    names: set[str],
    tail: list[str],
    fresh: dict[tuple[int, int], list[str]],
) -> list[tuple[int, int, str]]:
    model, text = an.model, an.text
    n = len(x.overrides)
    if n == 0:
        raise TransformError(model, f"{x.name}: forced reg without an override")
    for s in (
        "__base",
        "__ovr_sel",
        "__active",
        "__now",
        "__rd",
        *(f"__ovr_{k}" for k in range(1, n + 1)),
    ):
        if x.name + s in names:
            raise TransformError(model, f"{x.name}: the name {x.name}{s} is already used")
    w = max(1, n.bit_length())
    sel, base, now = f"{x.name}__ovr_sel", f"{x.name}__base", f"{x.name}__now"
    exprs = [text[e.start : e.end] for _, e in x.overrides]
    based = _WAIVE.format(base) if x.deassigns else base  # the declared X__base name

    # Forcing statements and substituted reads must not sit in a block with implicit
    # sensitivity: the rewrite changes what that block reads, hence when it re-runs.
    # A FRESH read there would make the block depend on X__ovr_sel/X__base: an event-driven
    # simulator would not re-run it on a release that leaves X unchanged, but Verilator,
    # which evaluates such a block as combinational logic, would (MMCME2_ADV).
    sites = [s for s, _ in x.overrides] + list(x.deassigns) + [r.span for r in x.stale_reads]
    for sp in sites:
        line = syn.implicit_block_line(sp.start)
        if line is not None:
            raise TransformError(
                model,
                f"{x.name}: procedural assign/deassign (or a read right after one) in the "
                f"block with implicit sensitivity at line {line}; the rewrite would change "
                "its sensitivity",
            )
    # Ruling S28 (module docstring). Only a reg with a deassign has the blocking capture
    # into X__base that races the masked commit; without one, X__base keeps only the
    # model's own writes and X__ovr_sel only blocking ones, so nothing is mixed.
    if x.nba_cone and x.deassigns:
        raise TransformError(
            model,
            f"{x.name}: trigger cone contains NBA-written reg {sorted(x.nba_cone)[0]}: the "
            "forcing block can run from the NBA region, where the shadow-register capture "
            "is not order-safe on Verilator (ruling S28)",
        )
    # The override expressions are re-evaluated at module scope (X__ovr_k, X__active):
    # every name they read must mean the same there.
    for (stmt, _), e in zip(x.overrides, exprs, strict=True):
        reads, local = syn.scoped_names(stmt.start)
        shadowed = sorted(reads & local)
        if shadowed:
            raise TransformError(
                model,
                f"{x.name}: override expression `{e}` reads {shadowed[0]}, which is declared "
                "in an enclosing generate block or named scope; it cannot be re-evaluated at "
                "module scope",
            )

    edits: list[tuple[int, int, str]] = []
    decl: list[str] = []
    if x.reg_keyword is not None:  # non-ANSI `output reg X;`: X becomes the port net
        after = text[x.decl_name.end : x.decl_end]
        if "=" in after:
            raise TransformError(
                model, f"{x.name}: `output reg` with an initialiser cannot be split"
            )
        edits.append((x.reg_keyword.start, x.reg_keyword.end, ""))
        decl.append(_var(x, based))
    else:
        edits.append((x.decl_name.start, x.decl_name.end, based))
    decl.append(f"reg [{w - 1}:0] {sel} = {w}'d0;")
    if not x.is_port:
        decl.append(_net(x, x.name))
    decl += [_net(x, f"{x.name}__ovr_{k}") for k in range(1, n + 1)]
    snap = {r.active for r in x.stale_reads if r.active not in (None, FRESH)}
    fresh_reads = sorted((r.span for r in x.stale_reads if r.active == FRESH), key=_start)
    if snap:
        decl.append(_var(x, now))
    if fresh_reads:
        decl.append(_var(x, f"{x.name}__rd"))
    edits.append((x.decl_end, x.decl_end, " " + " ".join(decl)))

    edits += [(s.start, s.end, base) for s in sorted(x.writes, key=lambda s: s.start)]
    for k, ((stmt, _), e) in enumerate(zip(x.overrides, exprs, strict=True), start=1):
        rep = f"{sel} = {w}'d{k};"
        if stmt in snap:
            rep = f"begin {rep} {now} = {e}; end"
        edits.append((stmt.start, stmt.end, rep))
        tail.append(f"  assign {x.name}__ovr_{k} = {e};")
    for d in x.deassigns:
        edits.append(
            (
                d.start,
                d.end,
                f"begin if ({sel} != {w}'d0) begin {base} = {x.name}__active(); "
                f"{sel} = {w}'d0; end end",  # outer begin/end: no dangling else (N1)
            )
        )
    for r in sorted(x.stale_reads, key=lambda r: r.span.start):
        if r.active != FRESH:
            edits.append((r.span.start, r.span.end, base if r.active is None else now))
    refresh = f"{x.name}__rd = ({sel} == {w}'d0) ? {base} : {x.name}__active();"
    for sp in fresh_reads:
        st = syn.statement(sp.start)
        line = syn.src.text.count("\n", 0, sp.start) + 1
        if st is None or st[2] in _LOOPS:
            where = "a loop header" if st is not None else "no procedural statement"
            raise TransformError(
                model,
                f"{x.name} is read in {where} at line {line} right after a blocking write; "
                "the read cannot be refreshed",
            )
        fresh.setdefault((st[0], st[1]), []).append(refresh)
        edits.append((sp.start, sp.end, f"{x.name}__rd"))

    mux = f"{x.name}__ovr_{n}"
    for k in range(n - 1, 0, -1):
        mux = f"({sel} == {w}'d{k}) ? {x.name}__ovr_{k} : {mux}"
    tail.append(f"  assign {x.name} = ({sel} == {w}'d0) ? {base} : {mux};")
    if x.deassigns or fresh_reads:
        tail.append(_function(x, exprs, w))
    return edits


def _start(sp: Span) -> int:
    return sp.start


def rewrite(an: Analysis) -> str:
    """The transformed text of ``an.path`` (the model and its same-file helper modules)."""
    syn = _Syntax(an.path)
    if syn.src.text != an.text:
        raise TransformError(an.model, f"{an.path} changed since it was analysed")
    names = set(re.findall(r"[A-Za-z_][A-Za-z0-9_$]*", an.text))
    edits: list[tuple[int, int, str]] = []
    edits += _module_edits(an, syn, names)
    for m in an.submodules.values():
        try:
            edits += _module_edits(m, syn, names)
        except TransformError as e:  # name the model, not only its helper
            raise TransformError(an.model, f"in helper module {e}") from e
    body = _apply(an.model, an.text, edits)
    if body.startswith(SPDX):  # the model's own SPDX line stays first, never duplicated
        body = body[len(SPDX) :]
    return SPDX + BANNER.format(src=an.path.name) + body


def write_text(path: Path, text: str) -> None:
    """Write rewritten model text byte-exactly (models are not all valid UTF-8)."""
    Path(path).write_bytes(text.encode("utf-8", "surrogateescape"))


def check_clean(text: str, model: str, glbl: Path, configs: list[dict[str, str]]) -> None:
    """Raise ``TransformError`` if any procedural ``assign``/``deassign`` remains (in any
    generate branch), or the text does not elaborate without errors under every
    configuration of ``configs`` (a missed ``X`` -> ``X__base`` rename is a procedural write
    to a net, an elaboration error)."""
    with tempfile.TemporaryDirectory() as d:
        f = Path(d) / f"{model}.v"
        write_text(f, text)
        tree = pyslang.syntax.SyntaxTree.fromFile(str(f))
        left = [n for n in _walk_syntax(tree.root) if n.kind in _SYNTAX_FORCE]
        if left:
            src = _Source(f)
            raise TransformError(
                model,
                "procedural assign/deassign remains after the rewrite at line "
                f"{src.line(left[0].sourceRange.start.offset)}",
            )
        for cfg in configs or [{}]:
            try:
                _compile(f, model, glbl, cfg)
            except TransformError as e:
                raise TransformError(model, f"rewritten model does not elaborate: {e}") from e
