# SPDX-License-Identifier: Apache-2.0
"""Harness slots (spec §7.1 "Multi-DUT packing"): what one bitstream holds, and the
RTL and constraints generated for it.

Slot 0 is the self-test passthrough and slot 1 the self-test counter; slots 2.. are
DUTs, one per test configuration. Each slot k has:

- ``in_s<k>``: its in_vec register, INIT = the configuration's ``t0``, written only by a
  COMMIT while ``sel == k``;
- ``dclk_s<k>_<i>``: one flip-flop per clock, INIT 0, written only by an EDGE while
  ``sel == k``, driving a BUFG whose output is the DUT's clk[i];
- for a DUT, the configuration's ``xut_dut`` wrapper renamed ``xut_dut_s<k>``.

A slot's digest covers what reaches the bitstream (kind, sizes, ``t0``, normalised
wrapper) and never a configuration name, so identical slots from different tests share
cached bitstreams.
"""

from __future__ import annotations

import hashlib
import re
from collections.abc import Sequence
from dataclasses import dataclass
from pathlib import Path

from xut.errors import XutError
from xut.hw.image import width
from xut.wrap import DutMap

HEADER = "// SPDX-License-Identifier: Apache-2.0"
HW_HDL = Path(__file__).resolve().parent.parent / "hdl" / "hw"
HW_SOURCES = (
    "xut_hw_top.sv",
    "xut_hw_ctrl.sv",
    "xut_hw_print.sv",
    "xut_hw_uart_tx.sv",
    "xut_hw_uart_rx.sv",
)
HW_INCLUDES = ("xut_hw_crc32.vh", "xut_hw_msgs.vh")
#: 7-series parts have 32 BUFGCTRL sites. The harness uses 2 (sysclk, the self-test
#: counter) and keeps 2 spare; DUT clocks get the rest.
DUT_BUFG_BUDGET = 28
MAX_SLOTS = 64
SYS_PERIOD_NS = 10.0
#: The generated RTL's field widths: 16-bit word counts, a 2-hex-digit margin, and a
#: max-delay of (margin - 2) system periods that must stay positive.
MAXWORDS_LIMIT = 0xFFFF
MARGIN_RANGE = (3, 255)
#: The primitives ``pack`` may put in a bitstream (ruling S59, fail closed). ``pack``
#: budgets only DUT clocks and the slot count, so a primitive is packable only if it uses
#: nothing else scarce: flip-flops, LUTs, carry and wide muxes, SRLs, LUTRAM and LUT ROM,
#: all in plentiful SLICE sites.
#:
#: TODO(hw packing): before any clocking, BRAM, DSP or configuration unit uses
#: ``--runner hw``, carry a per-site-type resource count on ``SlotBuild`` (from the
#: wrapper's cell types) and budget each in ``pack``: BUFGCTRL sites used inside DUTs
#: (BUFG/BUFGCE/BUFGMUX/BUFGCTRL share the 32 sites DUT_BUFG_BUDGET assumes free),
#: MMCME2/PLLE2 (5 each on the 35T), RAMB36/RAMB18 (50 RAMB36, minus the stimulus
#: memory's 8), DSP48E1 (90), the per-region BUFR/BUFIO/BUFH, IO sites, the singletons
#: (STARTUPE2, ICAPE2, DNA_PORT, XADC, ...) and the 12-global-clocks-per-region limit
#: behind DUT_BUFG_BUDGET. Then widen PACKABLE.
PACKABLE = re.compile(
    r"(FD\w*|LUT\w*|CFGLUT5|CARRY4|MUXF[78]|SRL\w*|RAM(32|64|128|256)\w*|ROM\w*)"
)
#: Latches fit in SLICE sites, but the wrapper drives their gate from in_vec, so they
#: have no clock and timing_tcl's out-of-DUT max-delay (which starts at the dclk_s*
#: clocks) never reaches the G -> cur_out path: spec 7.1's (N-2)-period bound would be
#: unconstrained (Task 4 re-review, Important 1).
#:
#: TODO(hw latches): before the latches unit uses ``--runner hw``, constrain the
#: in_vec -> G -> Q -> cur_out path (e.g. a -through max-delay on the latch G pins) and
#: move LD* into PACKABLE.
UNTIMED = re.compile(r"LD\w*")
_GEN_LINE = re.compile(r"^// GENERATED by xut wrap:.*\n", re.MULTILINE)
_DECL = "module xut_dut ("


class SlotError(XutError, ValueError):
    """A slot set the harness cannot hold."""


@dataclass(frozen=True)
class SlotBuild:
    kind: str  # passthrough | counter | dut
    nin: int
    nout: int
    nclk: int
    t0: str  # MSB-first width(nin) chars of 0/1
    wrapper: str = ""  # dut: the normalised xut_dut.v
    label: str = ""  # dut: the primitive, for comments
    map_json: str = ""  # dut: the wrapper's map, for the manifest (not in the digest)

    def digest(self) -> str:
        h = hashlib.sha256()
        for part in (
            self.kind,
            str(self.nin),
            str(self.nout),
            str(self.nclk),
            self.t0,
            self.wrapper,
        ):
            h.update(part.encode())
            h.update(b"\0")
        return h.hexdigest()


SELFTEST_SLOTS = (
    SlotBuild("passthrough", 16, 16, 0, "0" * 16),
    SlotBuild("counter", 2, 8, 1, "00"),
)


def normalize_wrapper(text: str) -> str:
    """``xut_dut.v`` without its configuration-naming GENERATED line."""
    text = _GEN_LINE.sub("", text)
    if text.count(_DECL) != 1:
        raise SlotError(f"expected exactly one {_DECL!r} in the wrapper")
    return text


def dut_slot(m: DutMap, wrapper_text: str, t0: str) -> SlotBuild:
    if len(t0) != width(m.nin) or set(t0) - {"0", "1"}:
        raise SlotError(f"t0 {t0!r} is not {width(m.nin)} bits of 0/1")
    return SlotBuild(
        "dut", m.nin, m.nout, m.nclk, t0, normalize_wrapper(wrapper_text), m.prim, m.to_json()
    )


def packable(prim: str) -> bool:
    """Whether ``pack`` may place a DUT of primitive ``prim`` (see ``PACKABLE``)."""
    return PACKABLE.fullmatch(prim) is not None


def pack(slots: Sequence[SlotBuild]) -> list[list[int]]:
    """Indices of DUT ``slots`` per bitstream: in digest order (so the same slot set packs
    the same way whichever test asks), greedily, until the next slot would exceed the
    DUT clock budget or MAX_SLOTS.

    Slots with the same digest are one slot in the bitstream: only the lowest index of
    each digest is placed, and the caller finds the others' slot by digest."""
    order = sorted(range(len(slots)), key=lambda i: (slots[i].digest(), i))
    groups: list[list[int]] = []
    cur: list[int] = []
    clocks = 0
    seen: set[str] = set()
    for i in order:
        s = slots[i]
        if s.kind != "dut":
            raise SlotError(f"slot {i} is a {s.kind}, not a DUT")
        if UNTIMED.fullmatch(s.label):
            raise SlotError(
                f"hw packing: {s.label} is a latch; its gate path out of the DUT is not "
                "yet timing-constrained — not yet supported"
            )
        if not packable(s.label):
            raise SlotError(
                f"hw packing: {s.label} needs resource budgeting "
                "(BUFG/MMCM/BRAM/DSP/IO/region) — not yet supported"
            )
        if s.nclk > DUT_BUFG_BUDGET:
            raise SlotError(
                f"a slot with {s.nclk} clocks exceeds the {DUT_BUFG_BUDGET}-BUFG budget"
            )
        if s.digest() in seen:
            continue
        seen.add(s.digest())
        full = clocks + s.nclk > DUT_BUFG_BUDGET or len(cur) + len(SELFTEST_SLOTS) >= MAX_SLOTS
        if cur and full:
            groups.append(cur)
            cur, clocks = [], 0
        cur.append(i)
        clocks += s.nclk
    if cur:
        groups.append(cur)
    return groups


def maxin(slots: Sequence[SlotBuild]) -> int:
    w = max(width(s.nin) for s in slots)
    return -(-w // 16) * 16


def maxout(slots: Sequence[SlotBuild]) -> int:
    return max(width(s.nout) for s in slots)


def _pad(expr: str, w: int, total: int) -> str:
    return expr if w == total else f"{{{total - w}'d0, {expr}}}"


def _slot(k: int, s: SlotBuild) -> list[str]:
    wi, wo = width(s.nin), width(s.nout)
    what = f"{s.kind} {s.label}".strip()
    out = [
        f"  // ---- slot {k}: {what} (nin {s.nin}, nclk {s.nclk}, nout {s.nout})",
        f'  (* DONT_TOUCH = "TRUE" *) reg [{wi - 1}:0] in_s{k} = {wi}\'b{s.t0};',
        f"  always @(posedge clk) if (commit && sel == 8'd{k}) in_s{k} <= in_nxt[{wi - 1}:0];",
    ]
    gclk = []
    for i in range(s.nclk):
        out += [
            f'  (* DONT_TOUCH = "TRUE" *) reg dclk_s{k}_{i} = 1\'b0;',
            f"  always @(posedge clk) if (edge_we && sel == 8'd{k} && edge_idx == 12'd{i}) "
            f"dclk_s{k}_{i} <= edge_val;",
            f"  wire gclk_s{k}_{i};",
            f"  BUFG u_bufg_s{k}_{i} (.I(dclk_s{k}_{i}), .O(gclk_s{k}_{i}));",
        ]
        gclk.append(f"gclk_s{k}_{i}")
    if s.kind == "passthrough":
        out.append(f"  wire [{wo - 1}:0] out_s{k} = in_s{k};")
    elif s.kind == "counter":
        out += [
            f"  reg [7:0] cnt_s{k} = 8'd0;",
            f"  always @(posedge gclk_s{k}_0) if (in_s{k}[1]) cnt_s{k} <= 8'd0; "
            f"else if (in_s{k}[0]) cnt_s{k} <= cnt_s{k} + 8'd1;",
            f"  wire [7:0] out_s{k} = cnt_s{k};",
        ]
    else:
        clk = "{" + ", ".join(reversed(gclk)) + "}" if gclk else "1'b0"
        out += [
            f"  wire [{width(s.nclk) - 1}:0] clk_s{k} = {clk};",
            f"  wire [{wo - 1}:0] out_s{k};",
            f"  xut_dut_s{k} u_dut_s{k} (.clk(clk_s{k}), .in_vec(in_s{k}), .out_vec(out_s{k}));",
        ]
    return out


def _check_slots(slots: Sequence[SlotBuild]) -> None:
    """A bitstream's slot list: SELFTEST_SLOTS, then DUTs within the clock budget and
    MAX_SLOTS."""
    if tuple(slots[:2]) != SELFTEST_SLOTS:
        raise SlotError("slots 0 and 1 must be the self-test channels (SELFTEST_SLOTS)")
    if len(slots) > MAX_SLOTS:
        raise SlotError(f"{len(slots)} slots > MAX_SLOTS={MAX_SLOTS}")
    for k, s in enumerate(slots[2:], start=2):
        if s.kind != "dut":
            raise SlotError(f"slot {k} is a {s.kind}, not a DUT")
    clocks = sum(s.nclk for s in slots[2:])
    if clocks > DUT_BUFG_BUDGET:
        raise SlotError(f"{clocks} DUT clocks exceed the {DUT_BUFG_BUDGET}-BUFG budget")


def _check_margin(margin: int) -> None:
    lo, hi = MARGIN_RANGE
    if not lo <= margin <= hi:
        raise SlotError(f"margin {margin} is outside {lo}..{hi}")


def render_slots(slots: Sequence[SlotBuild]) -> str:
    """``xut_hw_slots.v``: the slots module, then every DUT wrapper renamed per slot."""
    _check_slots(slots)
    mi, mo = maxin(slots), maxout(slots)
    out = [
        HEADER,
        f"// GENERATED by xut.hw.slots: {len(slots)} slots. Do not edit.",
        "`timescale 1ps / 1ps",
        "module xut_hw_slots (",
        "  input  wire        clk,",
        "  input  wire [7:0]  sel,",
        "  input  wire        commit,",
        f"  input  wire [{mi - 1}:0] in_nxt,",
        "  input  wire        edge_we,",
        "  input  wire [11:0] edge_idx,",
        "  input  wire        edge_val,",
        f"  output reg  [{mi - 1}:0] cur_in = {mi}'d0,",
        f"  output reg  [{mo - 1}:0] cur_out = {mo}'d0,",
        "  output reg  [15:0] cur_noutw = 16'd1",
        ");",
    ]
    for k, s in enumerate(slots):
        out += _slot(k, s)
    out += ["  always @(posedge clk) begin", "    case (sel)"]
    for k, s in enumerate(slots):
        wi, wo = width(s.nin), width(s.nout)
        out.append(
            f"      8'd{k}: begin cur_in <= {_pad(f'in_s{k}', wi, mi)}; "
            f"cur_out <= {_pad(f'out_s{k}', wo, mo)}; cur_noutw <= 16'd{wo}; end"
        )
    out += [
        f"      default: begin cur_in <= {mi}'d0; cur_out <= {mo}'d0; cur_noutw <= 16'd1; end",
        "    endcase",
        "  end",
        "endmodule",
        "",
    ]
    for k, s in enumerate(slots):
        if s.kind == "dut":
            out.append(s.wrapper.replace(_DECL, f"module xut_dut_s{k} (", 1))
    return "\n".join(out) + "\n"


def render_cfg_vh(slots: Sequence[SlotBuild], build_id: int, maxwords: int, margin: int) -> str:
    _check_slots(slots)
    _check_margin(margin)
    if not 1 <= maxwords <= MAXWORDS_LIMIT:
        raise SlotError(f"maxwords {maxwords} is outside 1..{MAXWORDS_LIMIT}")
    if not 0 <= build_id < 1 << 32:
        raise SlotError(f"build id {build_id:#x} is not 32 bits")
    return "\n".join(
        [
            HEADER,
            "// GENERATED by xut.hw.slots. Do not edit.",
            "`ifndef XUT_HW_CFG_VH",
            "`define XUT_HW_CFG_VH",
            f"`define XUT_HW_BUILD_ID 32'h{build_id:08x}",
            f"`define XUT_HW_NSLOTS {len(slots)}",
            f"`define XUT_HW_MAXIN {maxin(slots)}",
            f"`define XUT_HW_MAXOUT {maxout(slots)}",
            f"`define XUT_HW_MAXWORDS {maxwords}",
            f"`define XUT_HW_MARGIN {margin}",
            "`endif",
            "",
        ]
    )


def timing_tcl(slots: Sequence[SlotBuild], margin: int) -> str:
    """Constraints applied after synth_design (spec §7.1): a generated clock per DUT clock
    flip-flop, and max-delay (datapath only) of (MARGIN - 2) system periods into and out of
    the DUTs: every path from a slot's in_vec register, and every path from a DUT clock
    domain into the capture register ``cur_out``. (``set_max_delay -datapath_only`` needs a
    ``-from``; the combinational in_vec -> DUT -> cur_out paths are covered by the first.)
    Every object query goes through ``xut_must``: a constraint that matches nothing stops
    the build (exit 4). The self-test counter guarantees at least one DUT clock."""
    _check_slots(slots)
    _check_margin(margin)
    out = [
        "# SPDX-License-Identifier: Apache-2.0",
        "# GENERATED by xut.hw.slots: sourced after synth_design by build.tcl. Do not edit.",
        "proc xut_must {what objs} {",
        '  if {[llength $objs] == 0} { puts "XUT_CONSTRAINT_EMPTY $what"; exit 4 }',
        "  return $objs",
        "}",
        "xut_must sysclk [get_clocks sysclk]",
    ]
    for k, s in enumerate(slots):
        for i in range(s.nclk):
            ff = f"u_slots/dclk_s{k}_{i}_reg"
            out.append(
                f"create_generated_clock -name dclk_s{k}_{i} "
                f"-source [xut_must {ff}/C [get_pins {ff}/C]] -divide_by 2 "
                f"[xut_must {ff}/Q [get_pins {ff}/Q]]"
            )
    out += [
        f"set xut_margin_ns {(margin - 2) * SYS_PERIOD_NS:.3f}",
        "set_max_delay -datapath_only $xut_margin_ns -from [xut_must in_s "
        "[get_cells -hierarchical -filter {NAME =~ u_slots/in_s*_reg*}]]",
        "set_max_delay -datapath_only $xut_margin_ns -from [xut_must dclk "
        "[get_clocks dclk_s*]] -to [xut_must cur_out "
        "[get_pins -hierarchical -filter {NAME =~ u_slots/cur_out_reg*/D}]]",
        "",
    ]
    return "\n".join(out)
