# SPDX-License-Identifier: Apache-2.0
"""Command-line entry point."""

import subprocess
from collections import Counter
from datetime import UTC, datetime
from pathlib import Path

import click
import jsonschema
import yaml

from xut import __version__
from xut.errors import ConfigError, XutError

#: Marks status/PROGRESS.md, TODO.md and LOG.md as machine-generated (spec §11).
_GENERATED_COMMENT = "<!-- GENERATED by xut status generate — do not edit -->\n"


class _CleanErrorGroup(click.Group):
    """Root command group: any `XutError` raised by a subcommand becomes a clean
    `Error: <message>` and exit 1 (via `click.ClickException`), never a traceback.
    Nested groups propagate to this one, so every command shares the one handler."""

    def invoke(self, ctx: click.Context) -> object:
        try:
            return super().invoke(ctx)
        except XutError as e:
            raise click.ClickException(str(e)) from e


def _schema_error(path: Path, root: Path, e: Exception) -> ConfigError:
    """A `ConfigError` naming the offending file and the first schema/YAML problem."""
    rel = path.relative_to(root) if path.is_relative_to(root) else path
    if isinstance(e, jsonschema.ValidationError):
        return ConfigError(f"{rel}: {e.json_path}: {e.message}")
    return ConfigError(f"{rel}: invalid YAML: {str(e).splitlines()[0]}")


@click.group(cls=_CleanErrorGroup)
@click.version_option(__version__, prog_name="xut")
def main() -> None:
    """Xilinx primitive test-suite tooling."""


@main.command("fetch-docs")
@click.option("--local", type=click.Path(exists=True, dir_okay=False, path_type=Path))
def fetch_docs_cmd(local: Path | None) -> None:
    """Download UG953 into .cache/docs (or copy a local PDF there)."""
    from xut.docs_fetch import UG953, fetch, pdf_to_text
    from xut.paths import cache_dir

    pdf = fetch(UG953, cache_dir() / "docs", local=local)
    click.echo(f"pdf:  {pdf}\ntext: {pdf_to_text(pdf)}")


@main.group("catalog")
def catalog_grp() -> None:
    """Primitive catalog (catalog/<family>/<PRIM>.yaml)."""


EXPECTED_PRIMITIVES = 103


@catalog_grp.command("build")
def catalog_build_cmd() -> None:
    """Regenerate catalog/<family>/*.yaml and catalog/EXTRACTION_REPORT.md."""
    from xut.catalog.build import build_all, render_report
    from xut.catalog.ug953 import names_from_text
    from xut.docs_fetch import UG953, fetch, pdf_to_text
    from xut.paths import VIVADO_RETARGET, VIVADO_UNISIM, cache_dir, repo_root, submodule_unisim
    from xut.workunits import load_family

    text = pdf_to_text(fetch(UG953, cache_dir() / "docs"))
    names = names_from_text(text.read_text())
    if len(names) != EXPECTED_PRIMITIVES:
        raise click.ClickException(
            f"expected {EXPECTED_PRIMITIVES} UG953 primitive sections, found {len(names)}"
        )
    if VIVADO_UNISIM.is_dir():
        search = [VIVADO_UNISIM, VIVADO_RETARGET]
    else:
        search = [submodule_unisim()]
        click.echo(f"warning: {VIVADO_UNISIM} not found, using {search[0]}", err=True)
    root = repo_root()
    family = load_family(root)
    out = root / "catalog" / family
    report = build_all(text, names, out, search, family=family)
    sources = "the UNISIM models in " + ", ".join(f"`{s.name}/`" for s in search)
    (root / "catalog" / "EXTRACTION_REPORT.md").write_text(render_report(report, names, sources))
    only_in = sum(" only in " in line for line in report)
    click.echo(
        f"wrote {len(names)} entries to {out}; {len(report)} report lines ({only_in} only-in)"
    )


@main.group("status")
def status_grp() -> None:
    """Per-primitive status (status/<family>/<PRIM>.yaml, spec §11)."""


@status_grp.command("init")
def status_init_cmd() -> None:
    """Write a status stub for every catalog entry that has none yet.

    Never overwrites an existing status/<family>/<PRIM>.yaml.
    """
    from xut.catalog.model import load_entry
    from xut.paths import repo_root
    from xut.status import dump_stub
    from xut.workunits import load_family, load_units

    root = repo_root()
    family = load_family(root)
    unit_of = {p: name for name, u in load_units(root).items() for p in u.primitives}
    cat_dir = root / "catalog" / family
    out_dir = root / "status" / family
    out_dir.mkdir(parents=True, exist_ok=True)
    names = sorted(f.stem for f in cat_dir.glob("*.yaml") if not f.name.endswith(".overrides.yaml"))
    orphans = [n for n in names if n not in unit_of]
    if orphans:
        raise ConfigError(
            f"catalog primitive(s) in no work unit of docs/work-units.yaml: {', '.join(orphans)}"
        )
    written = 0
    for name in names:
        dest = out_dir / f"{name}.yaml"
        if dest.exists():
            continue
        entry = load_entry(family, name, root)
        dest.write_text(dump_stub(entry, unit_of[name]))
        written += 1
    click.echo(f"wrote {written} new stub(s); {len(names)} catalog entries, {out_dir}")


def _generated_header(root: Path, branch: str) -> str:
    """The header every generated status file starts with: the do-not-edit marker
    plus the generation time and git HEAD (spec §11; not part of any `render_*`
    function's output, so that output stays deterministic apart from this header)."""
    proc = subprocess.run(
        ["git", "rev-parse", "--short", "HEAD"], cwd=root, capture_output=True, text=True
    )
    head = proc.stdout.strip() if proc.returncode == 0 else "unknown"
    now = datetime.now(UTC).strftime("%Y-%m-%dT%H:%MZ")
    return _GENERATED_COMMENT + f"\n_Generated {now} at HEAD `{head}` on branch `{branch}`._\n\n"


@status_grp.command("generate")
@click.option("--force", is_flag=True, help="Write even when not on main.")
def status_generate_cmd(force: bool) -> None:
    """Regenerate status/PROGRESS.md, TODO.md and LOG.md (spec §11).

    Refuses unless the current branch is `main`, since branches never commit these
    generated files (spec §11, global constraints Review Focus item 5).
    """
    from xut.paths import repo_root
    from xut.status import current_branch, load_status, render_log, render_progress, render_todo
    from xut.workunits import load_family, load_units

    branch = current_branch()
    if branch != "main" and not force:
        raise click.ClickException(
            f"refusing to write generated status files on branch {branch!r}: "
            "only main regenerates them (pass --force to override)"
        )

    root = repo_root()
    units = load_units(root)
    status_dir = root / "status" / load_family(root)
    statuses = []
    for p in sorted(status_dir.glob("*.yaml")):
        try:
            statuses.append(load_status(p))
        except (yaml.YAMLError, jsonschema.ValidationError) as e:
            raise _schema_error(p, root, e) from e

    header = _generated_header(root, branch)
    out_dir = root / "status"
    (out_dir / "PROGRESS.md").write_text(header + render_progress(statuses, units))
    (out_dir / "TODO.md").write_text(header + render_todo(statuses, units))
    (out_dir / "LOG.md").write_text(header + render_log(root / "log"))
    click.echo(f"wrote PROGRESS.md, TODO.md, LOG.md to {out_dir} ({len(statuses)} statuses)")


@main.command("lint")
@click.option(
    "--branch",
    "branch_mode",
    is_flag=True,
    help="Also check branch-ownership and generated-file rules against <base>...HEAD.",
)
@click.option(
    "--base",
    default="origin/main",
    show_default=True,
    help="Base ref to diff against in --branch mode (e.g. origin/<PR base branch> in CI).",
)
def lint_cmd(branch_mode: bool, base: str) -> None:
    """Enforce branch ownership, SPDX headers, generated files, docs and status schema.

    Exits non-zero iff any error-severity issue was found; warnings are printed but never
    fail the build.
    """
    from xut.lint import lint
    from xut.paths import repo_root

    root = repo_root()
    issues, warnings = lint(root, branch_mode, base=base)
    for w in warnings:
        click.echo(f"warning: {w}", err=True)
    for issue in sorted(issues, key=lambda i: (i.path, i.rule)):
        click.echo(f"{issue.severity} {issue.rule} {issue.path}: {issue.message}")
    errors = sum(1 for i in issues if i.severity == "error")
    click.echo(f"{len(issues)} issue(s): {errors} error(s), {len(issues) - errors} warning(s)")
    if errors:
        raise SystemExit(1)


@main.group("container")
def container_grp() -> None:
    """The pinned simulator container (containers/sim)."""


@container_grp.command("build")
def container_build_cmd() -> None:
    """docker build -t xut-sim:<n> containers/sim (log: .cache/container-build.log)."""
    from xut import container
    from xut.paths import cache_dir, repo_root

    log = cache_dir() / "container-build.log"
    log.parent.mkdir(parents=True, exist_ok=True)
    argv = ["docker", "build", "-t", container.SIM_IMAGE, str(repo_root() / "containers/sim")]
    with log.open("w") as f:
        try:
            rc = subprocess.run(argv, stdout=f, stderr=subprocess.STDOUT).returncode
        except FileNotFoundError as e:
            raise click.ClickException("docker: command not found") from e
    if rc:
        raise click.ClickException(f"docker build failed (exit {rc}); see {log}")
    click.echo(f"{container.SIM_IMAGE} {container.image_digest(container.SIM_IMAGE)}")


@container_grp.command("versions")
def container_versions_cmd() -> None:
    """Print the pinned tool versions inside xut-sim."""
    from xut import container
    from xut.paths import repo_root

    work = repo_root() / "build"
    for k, v in container.sim_tool_versions(container.DockerExecutor(), work).items():
        click.echo(f"{k}: {v}")


@main.command("doctor")
def doctor_cmd() -> None:
    """Preflight checks: what's installed, and which runners it enables (spec §15).

    Always exits 0 — it's informational, not a gate.
    """
    from xut.doctor import available_runners, run_checks

    checks = run_checks()
    name_w = max(len(c.name) for c in checks)
    for c in checks:
        status = "OK" if c.ok else "MISSING"
        click.echo(f"{c.name:<{name_w}}  {status:<7}  {c.detail}")
    runners = available_runners(checks)
    click.echo("")
    click.echo(f"available runners: {', '.join(runners) if runners else '(none)'}")


@main.command("wrap")
@click.argument("prim")
@click.option("--cfg", default="default", show_default=True, help="configuration name")
@click.option("--attr", "attrs", multiple=True, help="NAME=VALUE (Verilog literal), repeatable")
@click.option("--out", type=click.Path(file_okay=False, path_type=Path), required=True)
@click.option("--cocotb-top", is_flag=True, help="also write xut_cocotb_top.v")
@click.option("--allow-illegal", is_flag=True, help="permit values outside the allowed list (L0)")
@click.option(
    "--raw-clock-out",
    is_flag=True,
    help="sample clock_out ports directly (equivalence/portability smoke runs only, spec §5.4)",
)
def wrap_cmd(
    prim: str,
    cfg: str,
    attrs: tuple[str, ...],
    out: Path,
    cocotb_top: bool,
    allow_illegal: bool,
    raw_clock_out: bool,
) -> None:
    """Generate xut_dut.v, xut_dut.map.json and xut_cfg.vh for one configuration (spec §5.2)."""
    from xut.catalog.model import load_entry
    from xut.paths import repo_root
    from xut.workunits import load_family
    from xut.wrap import WrapError, spec_from_catalog, write_dut

    pairs: dict[str, str] = {}
    for a in attrs:
        name, sep, value = a.partition("=")
        if not sep or not name:
            raise WrapError(f"--attr {a!r} is not NAME=VALUE")
        if name in pairs:
            raise WrapError(f"--attr {name} given twice")
        pairs[name] = value
    root = repo_root()
    family = load_family(root)
    if not (root / "catalog" / family / f"{prim}.yaml").is_file():
        raise WrapError(f"no catalog entry for {prim} (catalog/{family}/{prim}.yaml)")
    spec = spec_from_catalog(
        load_entry(family, prim, root),
        cfg,
        pairs,
        allow_illegal=allow_illegal,
        raw_clock_out=raw_clock_out,
    )
    m = write_dut(spec, out, cocotb_top=cocotb_top)
    click.echo(f"{out}: nclk={m.nclk} nin={m.nin} nout={m.nout}")


@main.group("vec")
def vec_grp() -> None:
    """Stimulus (.xvec) utilities."""


@vec_grp.command("check")
@click.argument("path", type=click.Path(exists=True, dir_okay=False, path_type=Path))
@click.option(
    "--map",
    "map_path",
    type=click.Path(exists=True, dir_okay=False, path_type=Path),
    required=True,
    help="the wrapper's xut_dut.map.json",
)
def vec_check_cmd(path: Path, map_path: Path) -> None:
    """Validate an .xvec against a wrapper map (spec §5.1 class rules).

    Prints every error and whether the file is hardware-renderable; exits 1 on errors.
    """
    from xut.formats.xvec import XvecError, load
    from xut.validate import validate
    from xut.wrap import DutMap

    try:
        vec = load(path)
    except XvecError as e:
        raise XvecError(f"{path}: {e}") from e
    r = validate(vec, DutMap.load(map_path))
    for e in r.errors:
        click.echo(f"error: {e}")
    if r.errors:  # an invalid file has no renderability (review A4)
        click.echo("hw_renderable: n/a (invalid)")
        raise SystemExit(1)
    click.echo(f"hw_renderable: {'yes' if r.hw_renderable else 'no'}")
    for h in r.hw_reasons:
        click.echo(f"  reason: {h}")
    # 2-state runners (Verilator, hw) must skip a stimulus that drives x/z.
    click.echo(f"x_inputs: {'yes' if r.x_inputs else 'no'}")


@main.command("run")
@click.argument("selectors", nargs=-1)
@click.option(
    "--runner",
    "runner_names",
    multiple=True,
    help="repeatable; default: every runner (iverilog-vz follows verilator)",
)
@click.option("--flow", type=click.Choice(["rtl"]), default="rtl", show_default=True)
@click.option("--model-source", default="auto", show_default=True)
@click.option("--style", "styles", multiple=True, type=click.Choice(["vector", "sv", "cocotb"]))
@click.option("--level", "levels", multiple=True, type=click.Choice(["L0", "L1", "L2", "L3"]))
@click.option(
    "--seed",
    type=int,
    help="stimulus/cocotb/sv seed (default: crc32 of the test id, the SAME on every run: "
    "pass --seed to explore others; every cocotb fail/error reason names its seed)",
)
@click.option("--jobs", type=click.IntRange(min=1), default=1, show_default=True)
@click.option("--timeout", type=click.IntRange(min=1), help="per-runner seconds (default 600)")
def run_cmd(
    selectors: tuple[str, ...],
    runner_names: tuple[str, ...],
    flow: str,
    model_source: str,
    styles: tuple[str, ...],
    levels: tuple[str, ...],
    seed: int | None,
    jobs: int,
    timeout: int | None,
) -> None:
    """Run tests: SELECT is a test-id glob, a primitive name or unit:<name> (default: all).

    Every selected (test, runner) pair writes
    build/<flow>/<runner>/<model-source>/<test-id>/result.json, and the run writes
    build/<flow>/summary-<model-source>.json. Exits 1 if any result is fail or error,
    or if a SELECT matches no test at all (filters leaving nothing selected exit 0).
    Skip reasons are printed, one line per distinct reason.
    """
    from xut import modelsrc
    from xut import run as run_mod
    from xut.paths import repo_root
    from xut.runners import RUNNERS
    from xut.runners.base import RunContext
    from xut.testspec import discover, select

    unknown = sorted(set(runner_names) - set(RUNNERS))
    if unknown:
        raise XutError(f"unknown runner(s) {unknown} (known: {sorted(RUNNERS)})")
    # iverilog-vz is not in the default list: it comes with verilator (spec §6.2)
    names = list(dict.fromkeys(runner_names)) or [r for r in RUNNERS if r != "iverilog-vz"]
    names = run_mod.with_companions(names)

    root = repo_root()
    cases = discover(root)
    if selectors:
        # A selector matching no test at all is an error (a typo must not pass in CI);
        # --level/--style filtering the matches down to nothing is not (exit 0 below).
        unmatched = [sel for sel in selectors if not select(cases, [sel])]
        if unmatched:
            raise XutError(f"no tests matched selector(s) {unmatched}")
        cases = select(cases, list(selectors))
    cases = [
        c for c in cases if (not levels or c.level in levels) and (not styles or c.style in styles)
    ]
    if not cases:
        what = [*selectors, *(f"--level {v}" for v in levels), *(f"--style {s}" for s in styles)]
        click.echo(f"no tests selected ({' '.join(what) or 'no tests under tests/'})")
        return

    ctx = RunContext(root, flow, modelsrc.resolve(model_source), seed, {}, timeout, jobs)
    try:
        results = run_mod.run_tests(cases, names, ctx)
    except KeyboardInterrupt:
        click.echo(
            "interrupted: queued runs cancelled; partial summary in "
            f"build/{flow}/summary-{ctx.model_source.name}.json",
            err=True,
        )
        raise SystemExit(130) from None

    ran = list(dict.fromkeys(r.runner for r in results))
    status = {(r.test_id, r.runner): r.status for r in results}
    id_w = max(len("test"), *(len(c.id) for c in cases))
    click.echo("")
    click.echo(f"{'test':<{id_w}}  " + "  ".join(f"{n:<{max(8, len(n))}}" for n in ran))
    for c in cases:
        cells = [f"{status.get((c.id, n), '-'):<{max(8, len(n))}}" for n in ran]
        click.echo(f"{c.id:<{id_w}}  " + "  ".join(cells))
    bad = [r for r in results if r.status in ("fail", "error")]
    for r in bad:
        click.echo(f"{r.status}: {r.test_id} {r.runner}: {r.reason}")
    skips = Counter(r.reason for r in results if r.status == "skip")
    for why, n in skips.items():
        click.echo(f"skip: {why} ({n} result{'s' if n > 1 else ''})")
    if bad:
        raise SystemExit(1)


@main.command("verilatorize")
@click.argument("models", nargs=-1)
@click.option("--model-source", default="auto", show_default=True)
@click.option("--jobs", type=click.IntRange(min=1), default=1, show_default=True)
@click.option(
    "--check",
    is_flag=True,
    help="Equivalence-check every transformed model against its original (spec §6.2).",
)
def verilatorize_cmd(models: tuple[str, ...], model_source: str, jobs: int, check: bool) -> None:
    """Rewrite procedural assign/deassign in UNISIM models for Verilator (spec §6.2).

    Writes build/verilatorized/<model-source>/<MODEL>.v and manifest.json (never
    committed). Incremental: a model is redone only when its source changed. MODEL
    restricts the run (default: every model of the source). --check then runs the
    mandatory equivalence stimulus on the original and the transformed model of every
    transformed model, under its default and every generate configuration, and of every
    model over a transformed dependency (its original hierarchy against the vz hierarchy,
    ruling S45); it exits 1 when any check is not a pass.
    """
    from xut import modelsrc
    from xut.verilatorize.driver import STATUSES, verilatorize, vz_dir

    ms = modelsrc.resolve(model_source)
    man = verilatorize(ms, list(models) or None, jobs=jobs, progress=click.echo, check=check)
    shown = {m: e for m, e in man.models.items() if not models or m in models}
    counts = Counter(e.status for e in shown.values())
    click.echo(
        f"{ms.name}: "
        + ", ".join(f"{counts.get(s, 0)} {s}" for s in STATUSES)
        + f" (output: {vz_dir(ms)})"
    )
    for m, e in sorted(shown.items()):
        if e.status == "transformed":
            click.echo(
                f"transformed: {m}: triggers={','.join(e.triggers)} "
                f"enablers={','.join(e.enablers) or '-'} configs={len(e.generate_configs)}"
            )
    for m, e in sorted(shown.items()):
        if e.status == "unsupported":
            why = e.reason.splitlines()[0]
            click.echo(f"unsupported: {m}: {why.removeprefix(f'{m}: ')}")
    for m, e in sorted(shown.items()):
        if e.status != "unsupported" and e.depends_on_unsupported:
            click.echo(f"blocked: {m}: its hierarchy holds {','.join(e.depends_on_unsupported)}")
        elif e.status == "unchanged" and e.depends_on_transformed:
            click.echo(f"gated: {m}: over {','.join(e.depends_on_transformed)}")
    if not check:
        return
    results: Counter[str] = Counter()
    for m, e in sorted(shown.items()):
        if not e.gated:
            continue
        for key, status in sorted(e.equiv.items()):
            results[status] += 1
            oracle = e.equiv_oracle.get(key) or "-"
            click.echo(f"equiv: {status}: {m} [{key}] oracle={oracle}")
    click.echo(
        "equiv: "
        + ", ".join(f"{results.get(s, 0)} {s}" for s in ("pass", "fail", "error"))
        + f" (details: {vz_dir(ms) / 'equiv'})"
    )
    if results.get("fail") or results.get("error"):
        raise SystemExit(1)
